local engine = require 'core.engine'
local lexicon = require 'core.lexicon'
local transliteration = require 'core.transliteration'
local encoding = require 'core.encoding'
assert(engine.translate('{~Keep  My TEXT!~}') == 'Keep  My TEXT!')
assert(engine.translate('{~' .. string.rep('long ', 30) .. '~}') == string.rep('long ', 30))
assert(engine.translate('{~=John Smith~}') == encoding.decode(transliteration.convert('John Smith', false)))
assert(engine.translate('{~a~} {~b~}.') == 'a b.')
assert(engine.translate('{~a~}{~b~}.') == 'ab.')
assert(engine.translate('{~a~}, {~b~}.') == 'a, b.')
local translated = engine.translate('Two books {~unchanged~}.')
assert(translated:find('unchanged', 1, true) and translated:find('книг', 1, true), translated)
assert(not pcall(engine.translate, '{~missing'))
assert(not pcall(engine.translate, '{~outer {~inner~}~}'))
local analyzed = lexicon.analyze(lexicon.from_bytes('word*Nслово\n'), '{~word~} word')
assert(analyzed.word_count == 1 and analyzed.vector[1].literal == 'word')
assert(analyzed.vector[2].reading == 'слово')
assert(engine.translate('{~Keep~}') == 'Keep', 'literal spans must not leak between calls')
local list,state=engine.translate('{~\\2 {~one~} {~two words~} {~three~} {~\\. Two books.')
assert(list=='one\ttwo words\nthree\n'..engine.translate('Two books.'),list)
assert(#state.sections==4 and state.output==encoding.encode(list))
assert(engine.translate('{~\\1 cat dog')==engine.translate('cat')..'\n'..engine.translate('dog'))
assert(engine.translate('{~\\10 {~one~} {~two~}')=='one\ttwo')
assert(engine.translate('{~\\2')=='')
assert(not pcall(engine.translate,'{~\\0 cat'))
assert(not pcall(engine.translate,'{~\\11 cat'))
assert(not pcall(engine.translate,'{~\\x cat'))
local gloss=engine.translate('{~\\1 agree', {meanings=true})
assert(gloss:find('agree',1,true))
print('directives_test: passed')
