; Supplied unpacked LTGOLD/LTPRO.EXE SHA256 6a2036c2fbc629d0317bf02acbb1e6ebd82ceecb2d11f609c6460cc0c32dc4fe
; Capstone x86 CS_MODE_16, 2026-10-06. Addresses are file offsets.
; Far-call operands retain original unrelocated segment:offset.
; Generated by disassembling the named half-open ranges below.

; Compiler block copy: 0x3E32..0x3E4E (end exclusive)
03E32 55             push     bp
03E33 8bec           mov      bp, sp
03E35 56             push     si
03E36 57             push     di
03E37 1e             push     ds
03E38 c57606         lds      si, ptr [bp + 6]
03E3B c47e0a         les      di, ptr [bp + 0xa]
03E3E fc             cld
03E3F d1e9           shr      cx, 1
03E41 f3a5           rep movsw word ptr es:[di], word ptr [si]
03E43 13c9           adc      cx, cx
03E45 f3a4           rep movsb byte ptr es:[di], byte ptr [si]
03E47 1f             pop      ds
03E48 5f             pop      di
03E49 5e             pop      si
03E4A 5d             pop      bp
03E4B ca0800         retf     8

; Exact string compare: 0x7711..0x7741 (end exclusive)
07711 55             push     bp
07712 8bec           mov      bp, sp
07714 56             push     si
07715 57             push     di
07716 8cda           mov      dx, ds
07718 fc             cld
07719 33c0           xor      ax, ax
0771B 8bd8           mov      bx, ax
0771D c47e0a         les      di, ptr [bp + 0xa]
07720 8bf7           mov      si, di
07722 32c0           xor      al, al
07724 b9ffff         mov      cx, 0xffff
07727 f2ae           repne scasb al, byte ptr es:[di]
07729 f7d1           not      cx
0772B 8bfe           mov      di, si
0772D c57606         lds      si, ptr [bp + 6]
07730 f3a6           repe cmpsb byte ptr [si], byte ptr es:[di]
07732 8a44ff         mov      al, byte ptr [si - 1]
07735 268a5dff       mov      bl, byte ptr es:[di - 1]
07739 2bc3           sub      ax, bx
0773B 8eda           mov      ds, dx
0773D 5f             pop      di
0773E 5e             pop      si
0773F 5d             pop      bp
07740 cb             retf

; ASCII case-insensitive compare: 0x77B0..0x77F1 (end exclusive)
077B0 55             push     bp
077B1 8bec           mov      bp, sp
077B3 56             push     si
077B4 57             push     di
077B5 8cda           mov      dx, ds
077B7 fc             cld
077B8 c57606         lds      si, ptr [bp + 6]
077BB c47e0a         les      di, ptr [bp + 0xa]
077BE 33c0           xor      ax, ax
077C0 8bd8           mov      bx, ax
077C2 b97a61         mov      cx, 0x617a
077C5 ac             lodsb    al, byte ptr [si]
077C6 268a1d         mov      bl, byte ptr es:[di]
077C9 0ac0           or       al, al
077CB 741c           je       0x77e9
077CD ae             scasb    al, byte ptr es:[di]
077CE 74f5           je       0x77c5
077D0 3ac5           cmp      al, ch
077D2 7206           jb       0x77da
077D4 3ac1           cmp      al, cl
077D6 7702           ja       0x77da
077D8 2c20           sub      al, 0x20
077DA 3add           cmp      bl, ch
077DC 7207           jb       0x77e5
077DE 3ad9           cmp      bl, cl
077E0 7703           ja       0x77e5
077E2 80eb20         sub      bl, 0x20
077E5 3ac3           cmp      al, bl
077E7 74dc           je       0x77c5
077E9 2bc3           sub      ax, bx
077EB 8eda           mov      ds, dx
077ED 5f             pop      di
077EE 5e             pop      si
077EF 5d             pop      bp
077F0 cb             retf

; Lexical replacement: 0x16CE4..0x1732D (end exclusive)
16CE4 55             push     bp
16CE5 8bec           mov      bp, sp
16CE7 81ec7001       sub      sp, 0x170
16CEB 56             push     si
16CEC 57             push     di
16CED 8b460a         mov      ax, word ptr [bp + 0xa]
16CF0 8946fe         mov      word ptr [bp - 2], ax
16CF3 c746fc0000     mov      word ptr [bp - 4], 0
16CF8 e90006         jmp      0x172fb
16CFB c45e12         les      bx, ptr [bp + 0x12]
16CFE 268a07         mov      al, byte ptr es:[bx]
16D01 b400           mov      ah, 0
16D03 3d2400         cmp      ax, 0x24
16D06 740b           je       0x16d13
16D08 3d2e00         cmp      ax, 0x2e
16D0B 7503           jne      0x16d10
16D0D e9f603         jmp      0x17106
16D10 e93404         jmp      0x17147
16D13 eb03           jmp      0x16d18
16D15 ff460e         inc      word ptr [bp + 0xe]
16D18 c45e0e         les      bx, ptr [bp + 0xe]
16D1B 26803f00       cmp      byte ptr es:[bx], 0
16D1F 7412           je       0x16d33
16D21 c45e0e         les      bx, ptr [bp + 0xe]
16D24 26803f3e       cmp      byte ptr es:[bx], 0x3e
16D28 7409           je       0x16d33
16D2A c45e0e         les      bx, ptr [bp + 0xe]
16D2D 26803f24       cmp      byte ptr es:[bx], 0x24
16D31 75e2           jne      0x16d15
16D33 c45e0e         les      bx, ptr [bp + 0xe]
16D36 268a07         mov      al, byte ptr es:[bx]
16D39 b400           mov      ah, 0
16D3B 0bc0           or       ax, ax
16D3D 7506           jne      0x16d45
16D3F 8b46fc         mov      ax, word ptr [bp - 4]
16D42 e9e205         jmp      0x17327
16D45 c45e0e         les      bx, ptr [bp + 0xe]
16D48 26807f013e     cmp      byte ptr es:[bx + 1], 0x3e
16D4D 7503           jne      0x16d52
16D4F ff460e         inc      word ptr [bp + 0xe]
16D52 8b460a         mov      ax, word ptr [bp + 0xa]
16D55 05aec5         add      ax, 0xc5ae
16D58 8c5ef2         mov      word ptr [bp - 0xe], ds
16D5B 8946f0         mov      word ptr [bp - 0x10], ax
16D5E c45e0e         les      bx, ptr [bp + 0xe]
16D61 26807f015b     cmp      byte ptr es:[bx + 1], 0x5b
16D66 7417           je       0x16d7f
16D68 c45e0e         les      bx, ptr [bp + 0xe]
16D6B 26807f0160     cmp      byte ptr es:[bx + 1], 0x60
16D70 740d           je       0x16d7f
16D72 c45e0e         les      bx, ptr [bp + 0xe]
16D75 26807f0121     cmp      byte ptr es:[bx + 1], 0x21
16D7A 7403           je       0x16d7f
16D7C e9a001         jmp      0x16f1f
16D7F 33ff           xor      di, di
16D81 83460e02       add      word ptr [bp + 0xe], 2
16D85 eb0d           jmp      0x16d94
16D87 c45e0e         les      bx, ptr [bp + 0xe]
16D8A 268a07         mov      al, byte ptr es:[bx]
16D8D 884394         mov      byte ptr [bp + di - 0x6c], al
16D90 ff460e         inc      word ptr [bp + 0xe]
16D93 47             inc      di
16D94 c45e0e         les      bx, ptr [bp + 0xe]
16D97 26803f00       cmp      byte ptr es:[bx], 0
16D9B 741b           je       0x16db8
16D9D c45e0e         les      bx, ptr [bp + 0xe]
16DA0 26803f5d       cmp      byte ptr es:[bx], 0x5d
16DA4 7412           je       0x16db8
16DA6 c45e0e         les      bx, ptr [bp + 0xe]
16DA9 26803f60       cmp      byte ptr es:[bx], 0x60
16DAD 7409           je       0x16db8
16DAF c45e0e         les      bx, ptr [bp + 0xe]
16DB2 26803f21       cmp      byte ptr es:[bx], 0x21
16DB6 75cf           jne      0x16d87
16DB8 c45e0e         les      bx, ptr [bp + 0xe]
16DBB 268a07         mov      al, byte ptr es:[bx]
16DBE b400           mov      ah, 0
16DC0 0bc0           or       ax, ax
16DC2 7503           jne      0x16dc7
16DC4 e978ff         jmp      0x16d3f
16DC7 c45e0e         les      bx, ptr [bp + 0xe]
16DCA 26803f21       cmp      byte ptr es:[bx], 0x21
16DCE 7505           jne      0x16dd5
16DD0 c6439429       mov      byte ptr [bp + di - 0x6c], 0x29
16DD4 47             inc      di
16DD5 c6439400       mov      byte ptr [bp + di - 0x6c], 0
16DD9 c45e0e         les      bx, ptr [bp + 0xe]
16DDC 26803f60       cmp      byte ptr es:[bx], 0x60
16DE0 7576           jne      0x16e58
16DE2 8b46f2         mov      ax, word ptr [bp - 0xe]
16DE5 8b56f0         mov      dx, word ptr [bp - 0x10]
16DE8 8946f6         mov      word ptr [bp - 0xa], ax
16DEB 8956f4         mov      word ptr [bp - 0xc], dx
16DEE 8b7e0a         mov      di, word ptr [bp + 0xa]
16DF1 eb54           jmp      0x16e47
16DF3 16             push     ss
16DF4 8d4694         lea      ax, [bp - 0x6c]
16DF7 50             push     ax
16DF8 8bc7           mov      ax, di
16DFA b102           mov      cl, 2
16DFC d3e0           shl      ax, cl
16DFE c45e06         les      bx, ptr [bp + 6]
16E01 03d8           add      bx, ax
16E03 268b07         mov      ax, word ptr es:[bx]
16E06 051200         add      ax, 0x12
16E09 26ff7702       push     word ptr es:[bx + 2]
16E0D 50             push     ax
16E0E 9ab03d0000     lcall    0, 0x3db0
16E13 83c408         add      sp, 8
16E16 0bc0           or       ax, ax
16E18 7427           je       0x16e41
16E1A 16             push     ss
16E1B 8d4694         lea      ax, [bp - 0x6c]
16E1E 50             push     ax
16E1F 8bc7           mov      ax, di
16E21 b102           mov      cl, 2
16E23 d3e0           shl      ax, cl
16E25 c45e06         les      bx, ptr [bp + 6]
16E28 03d8           add      bx, ax
16E2A 268b07         mov      ax, word ptr es:[bx]
16E2D 059c00         add      ax, 0x9c
16E30 26ff7702       push     word ptr es:[bx + 2]
16E34 50             push     ax
16E35 9a113d0000     lcall    0, 0x3d11
16E3A 83c408         add      sp, 8
16E3D 0bc0           or       ax, ax
16E3F 7502           jne      0x16e43
16E41 eb12           jmp      0x16e55
16E43 ff46f4         inc      word ptr [bp - 0xc]
16E46 47             inc      di
16E47 3b7e0c         cmp      di, word ptr [bp + 0xc]
16E4A 7f09           jg       0x16e55
16E4C c45ef4         les      bx, ptr [bp - 0xc]
16E4F 26803f00       cmp      byte ptr es:[bx], 0
16E53 759e           jne      0x16df3
16E55 e9a100         jmp      0x16ef9
16E58 c45e0e         les      bx, ptr [bp + 0xe]
16E5B 26803f21       cmp      byte ptr es:[bx], 0x21
16E5F 754e           jne      0x16eaf
16E61 8b46f2         mov      ax, word ptr [bp - 0xe]
16E64 8b56f0         mov      dx, word ptr [bp - 0x10]
16E67 8946f6         mov      word ptr [bp - 0xa], ax
16E6A 8956f4         mov      word ptr [bp - 0xc], dx
16E6D 8b7e0a         mov      di, word ptr [bp + 0xa]
16E70 eb2d           jmp      0x16e9f
16E72 16             push     ss
16E73 8d4694         lea      ax, [bp - 0x6c]
16E76 50             push     ax
16E77 8bc7           mov      ax, di
16E79 b102           mov      cl, 2
16E7B d3e0           shl      ax, cl
16E7D c45e06         les      bx, ptr [bp + 6]
16E80 03d8           add      bx, ax
16E82 268b07         mov      ax, word ptr es:[bx]
16E85 051c01         add      ax, 0x11c
16E88 26ff7702       push     word ptr es:[bx + 2]
16E8C 50             push     ax
16E8D 9ad93f0000     lcall    0, 0x3fd9
16E92 83c408         add      sp, 8
16E95 0bc2           or       ax, dx
16E97 7402           je       0x16e9b
16E99 eb12           jmp      0x16ead
16E9B ff46f4         inc      word ptr [bp - 0xc]
16E9E 47             inc      di
16E9F 3b7e0c         cmp      di, word ptr [bp + 0xc]
16EA2 7f09           jg       0x16ead
16EA4 c45ef4         les      bx, ptr [bp - 0xc]
16EA7 26803f00       cmp      byte ptr es:[bx], 0
16EAB 75c5           jne      0x16e72
16EAD eb4a           jmp      0x16ef9
16EAF 8b46f2         mov      ax, word ptr [bp - 0xe]
16EB2 8b56f0         mov      dx, word ptr [bp - 0x10]
16EB5 8946f6         mov      word ptr [bp - 0xa], ax
16EB8 8956f4         mov      word ptr [bp - 0xc], dx
16EBB 8b7e0a         mov      di, word ptr [bp + 0xa]
16EBE eb2b           jmp      0x16eeb
16EC0 8d4694         lea      ax, [bp - 0x6c]
16EC3 8c56ee         mov      word ptr [bp - 0x12], ss
16EC6 8946ec         mov      word ptr [bp - 0x14], ax
16EC9 eb13           jmp      0x16ede
16ECB c45ef4         les      bx, ptr [bp - 0xc]
16ECE 268a07         mov      al, byte ptr es:[bx]
16ED1 c45eec         les      bx, ptr [bp - 0x14]
16ED4 263a07         cmp      al, byte ptr es:[bx]
16ED7 7502           jne      0x16edb
16ED9 eb1e           jmp      0x16ef9
16EDB ff46ec         inc      word ptr [bp - 0x14]
16EDE c45eec         les      bx, ptr [bp - 0x14]
16EE1 26803f00       cmp      byte ptr es:[bx], 0
16EE5 75e4           jne      0x16ecb
16EE7 ff46f4         inc      word ptr [bp - 0xc]
16EEA 47             inc      di
16EEB 3b7e0c         cmp      di, word ptr [bp + 0xc]
16EEE 7f09           jg       0x16ef9
16EF0 c45ef4         les      bx, ptr [bp - 0xc]
16EF3 26803f00       cmp      byte ptr es:[bx], 0
16EF7 75c7           jne      0x16ec0
16EF9 c45ef4         les      bx, ptr [bp - 0xc]
16EFC 268a07         mov      al, byte ptr es:[bx]
16EFF b400           mov      ah, 0
16F01 0bc0           or       ax, ax
16F03 7405           je       0x16f0a
16F05 3b7e0c         cmp      di, word ptr [bp + 0xc]
16F08 7e03           jle      0x16f0d
16F0A e932fe         jmp      0x16d3f
16F0D 8b46f4         mov      ax, word ptr [bp - 0xc]
16F10 2b46f0         sub      ax, word ptr [bp - 0x10]
16F13 8946fa         mov      word ptr [bp - 6], ax
16F16 8b46fa         mov      ax, word ptr [bp - 6]
16F19 01460a         add      word ptr [bp + 0xa], ax
16F1C e9bf03         jmp      0x172de
16F1F 16             push     ss
16F20 8d8690fe       lea      ax, [bp - 0x170]
16F24 50             push     ax
16F25 ff36ea44       push     word ptr [0x44ea]
16F29 ff36e844       push     word ptr [0x44e8]
16F2D 8b460e         mov      ax, word ptr [bp + 0xe]
16F30 40             inc      ax
16F31 ff7610         push     word ptr [bp + 0x10]
16F34 50             push     ax
16F35 9a8c000421     lcall    0x2104, 0x8c
16F3A 83c40c         add      sp, 0xc
16F3D 0bc2           or       ax, dx
16F3F 7503           jne      0x16f44
16F41 e99a03         jmp      0x172de
16F44 16             push     ss
16F45 8d8690fe       lea      ax, [bp - 0x170]
16F49 50             push     ax
16F4A ff76f2         push     word ptr [bp - 0xe]
16F4D ff76f0         push     word ptr [bp - 0x10]
16F50 9ad93f0000     lcall    0, 0x3fd9
16F55 83c408         add      sp, 8
16F58 8956f6         mov      word ptr [bp - 0xa], dx
16F5B 8946f4         mov      word ptr [bp - 0xc], ax
16F5E 8b46f4         mov      ax, word ptr [bp - 0xc]
16F61 0b46f6         or       ax, word ptr [bp - 0xa]
16F64 7503           jne      0x16f69
16F66 e9d6fd         jmp      0x16d3f
16F69 16             push     ss
16F6A 8d8690fe       lea      ax, [bp - 0x170]
16F6E 50             push     ax
16F6F 9af13d0000     lcall    0, 0x3df1
16F74 59             pop      cx
16F75 59             pop      cx
16F76 8946f8         mov      word ptr [bp - 8], ax
16F79 8b46f4         mov      ax, word ptr [bp - 0xc]
16F7C 2b46f0         sub      ax, word ptr [bp - 0x10]
16F7F 8946fa         mov      word ptr [bp - 6], ax
16F82 8b46fa         mov      ax, word ptr [bp - 6]
16F85 01460a         add      word ptr [bp + 0xa], ax
16F88 8d8690fe       lea      ax, [bp - 0x170]
16F8C 8c56ea         mov      word ptr [bp - 0x16], ss
16F8F 8946e8         mov      word ptr [bp - 0x18], ax
16F92 e95301         jmp      0x170e8
16F95 ff4612         inc      word ptr [bp + 0x12]
16F98 c45e12         les      bx, ptr [bp + 0x12]
16F9B 268a07         mov      al, byte ptr es:[bx]
16F9E b400           mov      ah, 0
16FA0 0bc0           or       ax, ax
16FA2 7503           jne      0x16fa7
16FA4 e998fd         jmp      0x16d3f
16FA7 c45e12         les      bx, ptr [bp + 0x12]
16FAA 26803f20       cmp      byte ptr es:[bx], 0x20
16FAE 7505           jne      0x16fb5
16FB0 c746fc0100     mov      word ptr [bp - 4], 1
16FB5 c45e12         les      bx, ptr [bp + 0x12]
16FB8 26803f60       cmp      byte ptr es:[bx], 0x60
16FBC 7403           je       0x16fc1
16FBE e9ca00         jmp      0x1708b
16FC1 8b460a         mov      ax, word ptr [bp + 0xa]
16FC4 b102           mov      cl, 2
16FC6 d3e0           shl      ax, cl
16FC8 c45e06         les      bx, ptr [bp + 6]
16FCB 03d8           add      bx, ax
16FCD 268b4702       mov      ax, word ptr es:[bx + 2]
16FD1 268b17         mov      dx, word ptr es:[bx]
16FD4 8946e6         mov      word ptr [bp - 0x1a], ax
16FD7 8956e4         mov      word ptr [bp - 0x1c], dx
16FDA ff4612         inc      word ptr [bp + 0x12]
16FDD c45e12         les      bx, ptr [bp + 0x12]
16FE0 26803f3f       cmp      byte ptr es:[bx], 0x3f
16FE4 7409           je       0x16fef
16FE6 c45e12         les      bx, ptr [bp + 0x12]
16FE9 26803f40       cmp      byte ptr es:[bx], 0x40
16FED 7505           jne      0x16ff4
16FEF ff4612         inc      word ptr [bp + 0x12]
16FF2 eb48           jmp      0x1703c
16FF4 c45e12         les      bx, ptr [bp + 0x12]
16FF7 268a07         mov      al, byte ptr es:[bx]
16FFA b400           mov      ah, 0
16FFC 50             push     ax
16FFD 9a7f111e21     lcall    0x211e, 0x117f
17002 59             pop      cx
17003 0bc0           or       ax, ax
17005 7535           jne      0x1703c
17007 8b46e4         mov      ax, word ptr [bp - 0x1c]
1700A 0b46e6         or       ax, word ptr [bp - 0x1a]
1700D 742d           je       0x1703c
1700F c45ee4         les      bx, ptr [bp - 0x1c]
17012 268a470c       mov      al, byte ptr es:[bx + 0xc]
17016 c45ee4         les      bx, ptr [bp - 0x1c]
17019 26884766       mov      byte ptr es:[bx + 0x66], al
1701D 8b5e0a         mov      bx, word ptr [bp + 0xa]
17020 c47612         les      si, ptr [bp + 0x12]
17023 268a04         mov      al, byte ptr es:[si]
17026 8887aec5       mov      byte ptr [bx - 0x3a52], al
1702A c45ee4         les      bx, ptr [bp - 0x1c]
1702D 06             push     es
1702E c47612         les      si, ptr [bp + 0x12]
17031 268a04         mov      al, byte ptr es:[si]
17034 07             pop      es
17035 2688470c       mov      byte ptr es:[bx + 0xc], al
17039 ff4612         inc      word ptr [bp + 0x12]
1703C 8b46e4         mov      ax, word ptr [bp - 0x1c]
1703F 0b46e6         or       ax, word ptr [bp - 0x1a]
17042 7445           je       0x17089
17044 c45e12         les      bx, ptr [bp + 0x12]
17047 26803f00       cmp      byte ptr es:[bx], 0
1704B 743c           je       0x17089
1704D 33ff           xor      di, di
1704F eb16           jmp      0x17067
17051 c45ee4         les      bx, ptr [bp - 0x1c]
17054 03df           add      bx, di
17056 06             push     es
17057 c47612         les      si, ptr [bp + 0x12]
1705A 268a04         mov      al, byte ptr es:[si]
1705D 07             pop      es
1705E 2688871c01     mov      byte ptr es:[bx + 0x11c], al
17063 ff4612         inc      word ptr [bp + 0x12]
17066 47             inc      di
17067 c45e12         les      bx, ptr [bp + 0x12]
1706A 26803f00       cmp      byte ptr es:[bx], 0
1706E 740e           je       0x1707e
17070 c45e12         les      bx, ptr [bp + 0x12]
17073 26803f60       cmp      byte ptr es:[bx], 0x60
17077 7405           je       0x1707e
17079 83ff50         cmp      di, 0x50
1707C 7cd3           jl       0x17051
1707E c45ee4         les      bx, ptr [bp - 0x1c]
17081 03df           add      bx, di
17083 26c6871c0100   mov      byte ptr es:[bx + 0x11c], 0
17089 eb5a           jmp      0x170e5
1708B c45e12         les      bx, ptr [bp + 0x12]
1708E 26803f40       cmp      byte ptr es:[bx], 0x40
17092 7451           je       0x170e5
17094 8b5e0a         mov      bx, word ptr [bp + 0xa]
17097 c47612         les      si, ptr [bp + 0x12]
1709A 268a04         mov      al, byte ptr es:[si]
1709D 8887aec5       mov      byte ptr [bx - 0x3a52], al
170A1 8b460a         mov      ax, word ptr [bp + 0xa]
170A4 b102           mov      cl, 2
170A6 d3e0           shl      ax, cl
170A8 c45e06         les      bx, ptr [bp + 6]
170AB 03d8           add      bx, ax
170AD 26c41f         les      bx, ptr es:[bx]
170B0 268a470c       mov      al, byte ptr es:[bx + 0xc]
170B4 8b560a         mov      dx, word ptr [bp + 0xa]
170B7 b102           mov      cl, 2
170B9 d3e2           shl      dx, cl
170BB c45e06         les      bx, ptr [bp + 6]
170BE 03da           add      bx, dx
170C0 26c41f         les      bx, ptr es:[bx]
170C3 26884766       mov      byte ptr es:[bx + 0x66], al
170C7 8b460a         mov      ax, word ptr [bp + 0xa]
170CA b102           mov      cl, 2
170CC d3e0           shl      ax, cl
170CE c45e06         les      bx, ptr [bp + 6]
170D1 03d8           add      bx, ax
170D3 26c41f         les      bx, ptr es:[bx]
170D6 06             push     es
170D7 c47612         les      si, ptr [bp + 0x12]
170DA 268a04         mov      al, byte ptr es:[si]
170DD 07             pop      es
170DE 2688470c       mov      byte ptr es:[bx + 0xc], al
170E2 ff460a         inc      word ptr [bp + 0xa]
170E5 ff46e8         inc      word ptr [bp - 0x18]
170E8 c45e12         les      bx, ptr [bp + 0x12]
170EB 26803f00       cmp      byte ptr es:[bx], 0
170EF 740c           je       0x170fd
170F1 c45ee8         les      bx, ptr [bp - 0x18]
170F4 26803f00       cmp      byte ptr es:[bx], 0
170F8 7403           je       0x170fd
170FA e998fe         jmp      0x16f95
170FD 8b46f8         mov      ax, word ptr [bp - 8]
17100 01460e         add      word ptr [bp + 0xe], ax
17103 e9d801         jmp      0x172de
17106 c45e0e         les      bx, ptr [bp + 0xe]
17109 26803f7e       cmp      byte ptr es:[bx], 0x7e
1710D 7503           jne      0x17112
1710F ff460e         inc      word ptr [bp + 0xe]
17112 c45e0e         les      bx, ptr [bp + 0xe]
17115 26803f5b       cmp      byte ptr es:[bx], 0x5b
17119 7526           jne      0x17141
1711B eb03           jmp      0x17120
1711D ff460e         inc      word ptr [bp + 0xe]
17120 c45e0e         les      bx, ptr [bp + 0xe]
17123 26803f00       cmp      byte ptr es:[bx], 0
17127 7409           je       0x17132
17129 c45e0e         les      bx, ptr [bp + 0xe]
1712C 26803f5d       cmp      byte ptr es:[bx], 0x5d
17130 75eb           jne      0x1711d
17132 c45e0e         les      bx, ptr [bp + 0xe]
17135 268a07         mov      al, byte ptr es:[bx]
17138 b400           mov      ah, 0
1713A 0bc0           or       ax, ax
1713C 7503           jne      0x17141
1713E e9fefb         jmp      0x16d3f
17141 ff460a         inc      word ptr [bp + 0xa]
17144 e99701         jmp      0x172de
17147 c45e12         les      bx, ptr [bp + 0x12]
1714A 26803f20       cmp      byte ptr es:[bx], 0x20
1714E 7505           jne      0x17155
17150 c746fc0100     mov      word ptr [bp - 4], 1
17155 c45e12         les      bx, ptr [bp + 0x12]
17158 26803f60       cmp      byte ptr es:[bx], 0x60
1715C 7403           je       0x17161
1715E e9b100         jmp      0x17212
17161 8b460a         mov      ax, word ptr [bp + 0xa]
17164 b102           mov      cl, 2
17166 d3e0           shl      ax, cl
17168 c45e06         les      bx, ptr [bp + 6]
1716B 03d8           add      bx, ax
1716D 268b4702       mov      ax, word ptr es:[bx + 2]
17171 268b17         mov      dx, word ptr es:[bx]
17174 8946e6         mov      word ptr [bp - 0x1a], ax
17177 8956e4         mov      word ptr [bp - 0x1c], dx
1717A ff4612         inc      word ptr [bp + 0x12]
1717D c45e12         les      bx, ptr [bp + 0x12]
17180 26803f3f       cmp      byte ptr es:[bx], 0x3f
17184 7409           je       0x1718f
17186 c45e12         les      bx, ptr [bp + 0x12]
17189 26803f40       cmp      byte ptr es:[bx], 0x40
1718D 7505           jne      0x17194
1718F ff4612         inc      word ptr [bp + 0x12]
17192 eb40           jmp      0x171d4
17194 c45e12         les      bx, ptr [bp + 0x12]
17197 268a07         mov      al, byte ptr es:[bx]
1719A b400           mov      ah, 0
1719C 50             push     ax
1719D 9a7f111e21     lcall    0x211e, 0x117f
171A2 59             pop      cx
171A3 0bc0           or       ax, ax
171A5 752d           jne      0x171d4
171A7 c45ee4         les      bx, ptr [bp - 0x1c]
171AA 268a470c       mov      al, byte ptr es:[bx + 0xc]
171AE c45ee4         les      bx, ptr [bp - 0x1c]
171B1 26884766       mov      byte ptr es:[bx + 0x66], al
171B5 8b5e0a         mov      bx, word ptr [bp + 0xa]
171B8 c47612         les      si, ptr [bp + 0x12]
171BB 268a04         mov      al, byte ptr es:[si]
171BE 8887aec5       mov      byte ptr [bx - 0x3a52], al
171C2 c45ee4         les      bx, ptr [bp - 0x1c]
171C5 06             push     es
171C6 c47612         les      si, ptr [bp + 0x12]
171C9 268a04         mov      al, byte ptr es:[si]
171CC 07             pop      es
171CD 2688470c       mov      byte ptr es:[bx + 0xc], al
171D1 ff4612         inc      word ptr [bp + 0x12]
171D4 33ff           xor      di, di
171D6 eb16           jmp      0x171ee
171D8 c45ee4         les      bx, ptr [bp - 0x1c]
171DB 03df           add      bx, di
171DD 06             push     es
171DE c47612         les      si, ptr [bp + 0x12]
171E1 268a04         mov      al, byte ptr es:[si]
171E4 07             pop      es
171E5 2688871c01     mov      byte ptr es:[bx + 0x11c], al
171EA ff4612         inc      word ptr [bp + 0x12]
171ED 47             inc      di
171EE c45e12         les      bx, ptr [bp + 0x12]
171F1 26803f00       cmp      byte ptr es:[bx], 0
171F5 740e           je       0x17205
171F7 c45e12         les      bx, ptr [bp + 0x12]
171FA 26803f60       cmp      byte ptr es:[bx], 0x60
171FE 7405           je       0x17205
17200 83ff50         cmp      di, 0x50
17203 7cd3           jl       0x171d8
17205 c45ee4         les      bx, ptr [bp - 0x1c]
17208 03df           add      bx, di
1720A 26c6871c0100   mov      byte ptr es:[bx + 0x11c], 0
17210 eb57           jmp      0x17269
17212 c45e12         les      bx, ptr [bp + 0x12]
17215 26803f40       cmp      byte ptr es:[bx], 0x40
17219 744e           je       0x17269
1721B 8b460a         mov      ax, word ptr [bp + 0xa]
1721E b102           mov      cl, 2
17220 d3e0           shl      ax, cl
17222 c45e06         les      bx, ptr [bp + 6]
17225 03d8           add      bx, ax
17227 26c41f         les      bx, ptr es:[bx]
1722A 268a470c       mov      al, byte ptr es:[bx + 0xc]
1722E 8b560a         mov      dx, word ptr [bp + 0xa]
17231 b102           mov      cl, 2
17233 d3e2           shl      dx, cl
17235 c45e06         les      bx, ptr [bp + 6]
17238 03da           add      bx, dx
1723A 26c41f         les      bx, ptr es:[bx]
1723D 26884766       mov      byte ptr es:[bx + 0x66], al
17241 8b460a         mov      ax, word ptr [bp + 0xa]
17244 b102           mov      cl, 2
17246 d3e0           shl      ax, cl
17248 c45e06         les      bx, ptr [bp + 6]
1724B 03d8           add      bx, ax
1724D 26c41f         les      bx, ptr es:[bx]
17250 06             push     es
17251 c47612         les      si, ptr [bp + 0x12]
17254 268a04         mov      al, byte ptr es:[si]
17257 07             pop      es
17258 2688470c       mov      byte ptr es:[bx + 0xc], al
1725C 8b5e0a         mov      bx, word ptr [bp + 0xa]
1725F c47612         les      si, ptr [bp + 0x12]
17262 268a04         mov      al, byte ptr es:[si]
17265 8887aec5       mov      byte ptr [bx - 0x3a52], al
17269 ff460a         inc      word ptr [bp + 0xa]
1726C c45e0e         les      bx, ptr [bp + 0xe]
1726F 26803f7e       cmp      byte ptr es:[bx], 0x7e
17273 7503           jne      0x17278
17275 ff460e         inc      word ptr [bp + 0xe]
17278 c45e0e         les      bx, ptr [bp + 0xe]
1727B 26803f5b       cmp      byte ptr es:[bx], 0x5b
1727F 7519           jne      0x1729a
17281 eb03           jmp      0x17286
17283 ff460e         inc      word ptr [bp + 0xe]
17286 c45e0e         les      bx, ptr [bp + 0xe]
17289 26803f00       cmp      byte ptr es:[bx], 0
1728D 7409           je       0x17298
1728F c45e0e         les      bx, ptr [bp + 0xe]
17292 26803f5d       cmp      byte ptr es:[bx], 0x5d
17296 75eb           jne      0x17283
17298 eb42           jmp      0x172dc
1729A c45e0e         les      bx, ptr [bp + 0xe]
1729D 26803f60       cmp      byte ptr es:[bx], 0x60
172A1 7519           jne      0x172bc
172A3 eb00           jmp      0x172a5
172A5 ff460e         inc      word ptr [bp + 0xe]
172A8 c45e0e         les      bx, ptr [bp + 0xe]
172AB 26803f00       cmp      byte ptr es:[bx], 0
172AF 7409           je       0x172ba
172B1 c45e0e         les      bx, ptr [bp + 0xe]
172B4 26803f60       cmp      byte ptr es:[bx], 0x60
172B8 75eb           jne      0x172a5
172BA eb20           jmp      0x172dc
172BC c45e0e         les      bx, ptr [bp + 0xe]
172BF 26803f21       cmp      byte ptr es:[bx], 0x21
172C3 7517           jne      0x172dc
172C5 eb00           jmp      0x172c7
172C7 ff460e         inc      word ptr [bp + 0xe]
172CA c45e0e         les      bx, ptr [bp + 0xe]
172CD 26803f00       cmp      byte ptr es:[bx], 0
172D1 7409           je       0x172dc
172D3 c45e0e         les      bx, ptr [bp + 0xe]
172D6 26803f21       cmp      byte ptr es:[bx], 0x21
172DA 75eb           jne      0x172c7
172DC eb00           jmp      0x172de
172DE c45e0e         les      bx, ptr [bp + 0xe]
172E1 26803f00       cmp      byte ptr es:[bx], 0
172E5 7403           je       0x172ea
172E7 ff460e         inc      word ptr [bp + 0xe]
172EA c45e12         les      bx, ptr [bp + 0x12]
172ED 268a07         mov      al, byte ptr es:[bx]
172F0 b400           mov      ah, 0
172F2 0bc0           or       ax, ax
172F4 7502           jne      0x172f8
172F6 eb2c           jmp      0x17324
172F8 ff4612         inc      word ptr [bp + 0x12]
172FB c45e12         les      bx, ptr [bp + 0x12]
172FE 26803f00       cmp      byte ptr es:[bx], 0
17302 7420           je       0x17324
17304 8b460a         mov      ax, word ptr [bp + 0xa]
17307 3b460c         cmp      ax, word ptr [bp + 0xc]
1730A 7f18           jg       0x17324
1730C 8b460a         mov      ax, word ptr [bp + 0xa]
1730F b102           mov      cl, 2
17311 d3e0           shl      ax, cl
17313 c45e06         les      bx, ptr [bp + 6]
17316 03d8           add      bx, ax
17318 268b07         mov      ax, word ptr es:[bx]
1731B 260b4702       or       ax, word ptr es:[bx + 2]
1731F 7403           je       0x17324
17321 e9d7f9         jmp      0x16cfb
17324 e918fa         jmp      0x16d3f
17327 5f             pop      di
17328 5e             pop      si
17329 8be5           mov      sp, bp
1732B 5d             pop      bp
1732C cb             retf

; Set and lexical-alternative helpers: 0x17367..0x17597 (end exclusive)
17367 55             push     bp
17368 8bec           mov      bp, sp
1736A eb22           jmp      0x1738e
1736C c45e0a         les      bx, ptr [bp + 0xa]
1736F 268a07         mov      al, byte ptr es:[bx]
17372 b400           mov      ah, 0
17374 50             push     ax
17375 ff7608         push     word ptr [bp + 8]
17378 ff7606         push     word ptr [bp + 6]
1737B 9ad43c0000     lcall    0, 0x3cd4
17380 83c406         add      sp, 6
17383 0bc2           or       ax, dx
17385 7504           jne      0x1738b
17387 33c0           xor      ax, ax
17389 eb11           jmp      0x1739c
1738B ff460a         inc      word ptr [bp + 0xa]
1738E c45e0a         les      bx, ptr [bp + 0xa]
17391 26803f00       cmp      byte ptr es:[bx], 0
17395 75d5           jne      0x1736c
17397 b80100         mov      ax, 1
1739A ebed           jmp      0x17389
1739C 5d             pop      bp
1739D cb             retf
1739E 55             push     bp
1739F 8bec           mov      bp, sp
173A1 eb23           jmp      0x173c6
173A3 c45e0a         les      bx, ptr [bp + 0xa]
173A6 268a07         mov      al, byte ptr es:[bx]
173A9 b400           mov      ah, 0
173AB 50             push     ax
173AC ff7608         push     word ptr [bp + 8]
173AF ff7606         push     word ptr [bp + 6]
173B2 9ad43c0000     lcall    0, 0x3cd4
173B7 83c406         add      sp, 6
173BA 0bc2           or       ax, dx
173BC 7405           je       0x173c3
173BE b80100         mov      ax, 1
173C1 eb10           jmp      0x173d3
173C3 ff460a         inc      word ptr [bp + 0xa]
173C6 c45e0a         les      bx, ptr [bp + 0xa]
173C9 26803f00       cmp      byte ptr es:[bx], 0
173CD 75d4           jne      0x173a3
173CF 33c0           xor      ax, ax
173D1 ebee           jmp      0x173c1
173D3 5d             pop      bp
173D4 cb             retf
173D5 55             push     bp
173D6 8bec           mov      bp, sp
173D8 56             push     si
173D9 57             push     di
173DA 8b760a         mov      si, word ptr [bp + 0xa]
173DD e9ca00         jmp      0x174aa
173E0 33ff           xor      di, di
173E2 e9bc00         jmp      0x174a1
173E5 b82900         mov      ax, 0x29
173E8 50             push     ax
173E9 8bc7           mov      ax, di
173EB ba2800         mov      dx, 0x28
173EE f7ea           imul     dx
173F0 8b560e         mov      dx, word ptr [bp + 0xe]
173F3 03d0           add      dx, ax
173F5 ff7610         push     word ptr [bp + 0x10]
173F8 52             push     dx
173F9 9ad43c0000     lcall    0, 0x3cd4
173FE 83c406         add      sp, 6
17401 0bc2           or       ax, dx
17403 7432           je       0x17437
17405 8bc7           mov      ax, di
17407 ba2800         mov      dx, 0x28
1740A f7ea           imul     dx
1740C 8b560e         mov      dx, word ptr [bp + 0xe]
1740F 03d0           add      dx, ax
17411 ff7610         push     word ptr [bp + 0x10]
17414 52             push     dx
17415 8bc6           mov      ax, si
17417 b102           mov      cl, 2
17419 d3e0           shl      ax, cl
1741B c45e06         les      bx, ptr [bp + 6]
1741E 03d8           add      bx, ax
17420 268b07         mov      ax, word ptr es:[bx]
17423 051c01         add      ax, 0x11c
17426 26ff7702       push     word ptr es:[bx + 2]
1742A 50             push     ax
1742B 9ad93f0000     lcall    0, 0x3fd9
17430 83c408         add      sp, 8
17433 0bc2           or       ax, dx
17435 7564           jne      0x1749b
17437 8bc7           mov      ax, di
17439 ba2800         mov      dx, 0x28
1743C f7ea           imul     dx
1743E 8b560e         mov      dx, word ptr [bp + 0xe]
17441 03d0           add      dx, ax
17443 ff7610         push     word ptr [bp + 0x10]
17446 52             push     dx
17447 8bc6           mov      ax, si
17449 b102           mov      cl, 2
1744B d3e0           shl      ax, cl
1744D c45e06         les      bx, ptr [bp + 6]
17450 03d8           add      bx, ax
17452 268b07         mov      ax, word ptr es:[bx]
17455 051200         add      ax, 0x12
17458 26ff7702       push     word ptr es:[bx + 2]
1745C 50             push     ax
1745D 9ab03d0000     lcall    0, 0x3db0
17462 83c408         add      sp, 8
17465 0bc0           or       ax, ax
17467 7432           je       0x1749b
17469 8bc7           mov      ax, di
1746B ba2800         mov      dx, 0x28
1746E f7ea           imul     dx
17470 8b560e         mov      dx, word ptr [bp + 0xe]
17473 03d0           add      dx, ax
17475 ff7610         push     word ptr [bp + 0x10]
17478 52             push     dx
17479 8bc6           mov      ax, si
1747B b102           mov      cl, 2
1747D d3e0           shl      ax, cl
1747F c45e06         les      bx, ptr [bp + 6]
17482 03d8           add      bx, ax
17484 268b07         mov      ax, word ptr es:[bx]
17487 059c00         add      ax, 0x9c
1748A 26ff7702       push     word ptr es:[bx + 2]
1748E 50             push     ax
1748F 9a113d0000     lcall    0, 0x3d11
17494 83c408         add      sp, 8
17497 0bc0           or       ax, ax
17499 7505           jne      0x174a0
1749B b80100         mov      ax, 1
1749E eb1a           jmp      0x174ba
174A0 47             inc      di
174A1 3b7e12         cmp      di, word ptr [bp + 0x12]
174A4 7f03           jg       0x174a9
174A6 e93cff         jmp      0x173e5
174A9 46             inc      si
174AA 8bc6           mov      ax, si
174AC 03460c         add      ax, word ptr [bp + 0xc]
174AF 3bc6           cmp      ax, si
174B1 7e03           jle      0x174b6
174B3 e92aff         jmp      0x173e0
174B6 33c0           xor      ax, ax
174B8 ebe4           jmp      0x1749e
174BA 5f             pop      di
174BB 5e             pop      si
174BC 5d             pop      bp
174BD cb             retf
174BE 55             push     bp
174BF 8bec           mov      bp, sp
174C1 56             push     si
174C2 57             push     di
174C3 8b7e0a         mov      di, word ptr [bp + 0xa]
174C6 33f6           xor      si, si
174C8 e9bc00         jmp      0x17587
174CB b82900         mov      ax, 0x29
174CE 50             push     ax
174CF 8bc6           mov      ax, si
174D1 ba2800         mov      dx, 0x28
174D4 f7ea           imul     dx
174D6 8b560c         mov      dx, word ptr [bp + 0xc]
174D9 03d0           add      dx, ax
174DB ff760e         push     word ptr [bp + 0xe]
174DE 52             push     dx
174DF 9ad43c0000     lcall    0, 0x3cd4
174E4 83c406         add      sp, 6
174E7 0bc2           or       ax, dx
174E9 7432           je       0x1751d
174EB 8bc6           mov      ax, si
174ED ba2800         mov      dx, 0x28
174F0 f7ea           imul     dx
174F2 8b560c         mov      dx, word ptr [bp + 0xc]
174F5 03d0           add      dx, ax
174F7 ff760e         push     word ptr [bp + 0xe]
174FA 52             push     dx
174FB 8bc7           mov      ax, di
174FD b102           mov      cl, 2
174FF d3e0           shl      ax, cl
17501 c45e06         les      bx, ptr [bp + 6]
17504 03d8           add      bx, ax
17506 268b07         mov      ax, word ptr es:[bx]
17509 051c01         add      ax, 0x11c
1750C 26ff7702       push     word ptr es:[bx + 2]
17510 50             push     ax
17511 9ad93f0000     lcall    0, 0x3fd9
17516 83c408         add      sp, 8
17519 0bc2           or       ax, dx
1751B 7564           jne      0x17581
1751D 8bc6           mov      ax, si
1751F ba2800         mov      dx, 0x28
17522 f7ea           imul     dx
17524 8b560c         mov      dx, word ptr [bp + 0xc]
17527 03d0           add      dx, ax
17529 ff760e         push     word ptr [bp + 0xe]
1752C 52             push     dx
1752D 8bc7           mov      ax, di
1752F b102           mov      cl, 2
17531 d3e0           shl      ax, cl
17533 c45e06         les      bx, ptr [bp + 6]
17536 03d8           add      bx, ax
17538 268b07         mov      ax, word ptr es:[bx]
1753B 051200         add      ax, 0x12
1753E 26ff7702       push     word ptr es:[bx + 2]
17542 50             push     ax
17543 9ab03d0000     lcall    0, 0x3db0
17548 83c408         add      sp, 8
1754B 0bc0           or       ax, ax
1754D 7432           je       0x17581
1754F 8bc6           mov      ax, si
17551 ba2800         mov      dx, 0x28
17554 f7ea           imul     dx
17556 8b560c         mov      dx, word ptr [bp + 0xc]
17559 03d0           add      dx, ax
1755B ff760e         push     word ptr [bp + 0xe]
1755E 52             push     dx
1755F 8bc7           mov      ax, di
17561 b102           mov      cl, 2
17563 d3e0           shl      ax, cl
17565 c45e06         les      bx, ptr [bp + 6]
17568 03d8           add      bx, ax
1756A 268b07         mov      ax, word ptr es:[bx]
1756D 059c00         add      ax, 0x9c
17570 26ff7702       push     word ptr es:[bx + 2]
17574 50             push     ax
17575 9a113d0000     lcall    0, 0x3d11
1757A 83c408         add      sp, 8
1757D 0bc0           or       ax, ax
1757F 7505           jne      0x17586
17581 b80100         mov      ax, 1
17584 eb0d           jmp      0x17593
17586 46             inc      si
17587 3b7610         cmp      si, word ptr [bp + 0x10]
1758A 7f03           jg       0x1758f
1758C e93cff         jmp      0x174cb
1758F 33c0           xor      ax, ax
17591 ebf1           jmp      0x17584
17593 5f             pop      di
17594 5e             pop      si
17595 5d             pop      bp
17596 cb             retf

; Lexical matcher: 0x17597..0x17DF7 (end exclusive)
17597 55             push     bp
17598 8bec           mov      bp, sp
1759A 81ec4803       sub      sp, 0x348
1759E 56             push     si
1759F 57             push     di
175A0 c746fe0000     mov      word ptr [bp - 2], 0
175A5 c746fa0000     mov      word ptr [bp - 6], 0
175AA 8d8648ff       lea      ax, [bp - 0xb8]
175AE 16             push     ss
175AF 50             push     ax
175B0 b8ec44         mov      ax, 0x44ec
175B3 1e             push     ds
175B4 50             push     ax
175B5 b95000         mov      cx, 0x50
175B8 9a32040000     lcall    0, 0x432
175BD e91e08         jmp      0x17dde
175C0 c45e0c         les      bx, ptr [bp + 0xc]
175C3 268a07         mov      al, byte ptr es:[bx]
175C6 b400           mov      ah, 0
175C8 8946e8         mov      word ptr [bp - 0x18], ax
175CB b90600         mov      cx, 6
175CE bbc712         mov      bx, 0x12c7
175D1 2e8b07         mov      ax, word ptr cs:[bx]
175D4 3b46e8         cmp      ax, word ptr [bp - 0x18]
175D7 7408           je       0x175e1
175D9 83c302         add      bx, 2
175DC e2f3           loop     0x175d1
175DE e99d07         jmp      0x17d7e
175E1 2eff670c       jmp      word ptr cs:[bx + 0xc]
175E5 c45e0c         les      bx, ptr [bp + 0xc]
175E8 268a07         mov      al, byte ptr es:[bx]
175EB b400           mov      ah, 0
175ED 8946fe         mov      word ptr [bp - 2], ax
175F0 e9da07         jmp      0x17dcd
175F3 33ff           xor      di, di
175F5 ff460c         inc      word ptr [bp + 0xc]
175F8 eb0d           jmp      0x17607
175FA c45e0c         les      bx, ptr [bp + 0xc]
175FD 268a07         mov      al, byte ptr es:[bx]
17600 884398         mov      byte ptr [bp + di - 0x68], al
17603 ff460c         inc      word ptr [bp + 0xc]
17606 47             inc      di
17607 c45e0c         les      bx, ptr [bp + 0xc]
1760A 26803f00       cmp      byte ptr es:[bx], 0
1760E 741b           je       0x1762b
17610 c45e0c         les      bx, ptr [bp + 0xc]
17613 26803f5d       cmp      byte ptr es:[bx], 0x5d
17617 7412           je       0x1762b
17619 c45e0c         les      bx, ptr [bp + 0xc]
1761C 26803f60       cmp      byte ptr es:[bx], 0x60
17620 7409           je       0x1762b
17622 c45e0c         les      bx, ptr [bp + 0xc]
17625 26803f21       cmp      byte ptr es:[bx], 0x21
17629 75cf           jne      0x175fa
1762B c6439800       mov      byte ptr [bp + di - 0x68], 0
1762F 807e9824       cmp      byte ptr [bp - 0x68], 0x24
17633 750c           jne      0x17641
17635 8a4699         mov      al, byte ptr [bp - 0x67]
17638 b400           mov      ah, 0
1763A 0bc0           or       ax, ax
1763C 7503           jne      0x17641
1763E e98707         jmp      0x17dc8
17641 c746fa0000     mov      word ptr [bp - 6], 0
17646 e99100         jmp      0x176da
17649 33ff           xor      di, di
1764B ff460c         inc      word ptr [bp + 0xc]
1764E eb1f           jmp      0x1766f
17650 8b46fa         mov      ax, word ptr [bp - 6]
17653 ba2800         mov      dx, 0x28
17656 f7ea           imul     dx
17658 03c7           add      ax, di
1765A 8d96b8fd       lea      dx, [bp - 0x248]
1765E 03c2           add      ax, dx
17660 c45e0c         les      bx, ptr [bp + 0xc]
17663 268a17         mov      dl, byte ptr es:[bx]
17666 8bd8           mov      bx, ax
17668 368817         mov      byte ptr ss:[bx], dl
1766B ff460c         inc      word ptr [bp + 0xc]
1766E 47             inc      di
1766F c45e0c         les      bx, ptr [bp + 0xc]
17672 26803f00       cmp      byte ptr es:[bx], 0
17676 7412           je       0x1768a
17678 c45e0c         les      bx, ptr [bp + 0xc]
1767B 26803f60       cmp      byte ptr es:[bx], 0x60
1767F 7409           je       0x1768a
17681 c45e0c         les      bx, ptr [bp + 0xc]
17684 26803f21       cmp      byte ptr es:[bx], 0x21
17688 75c6           jne      0x17650
1768A c45e0c         les      bx, ptr [bp + 0xc]
1768D 268a07         mov      al, byte ptr es:[bx]
17690 b400           mov      ah, 0
17692 0bc0           or       ax, ax
17694 7505           jne      0x1769b
17696 33c0           xor      ax, ax
17698 e95607         jmp      0x17df1
1769B c45e0c         les      bx, ptr [bp + 0xc]
1769E 26803f21       cmp      byte ptr es:[bx], 0x21
176A2 7517           jne      0x176bb
176A4 8b46fa         mov      ax, word ptr [bp - 6]
176A7 ba2800         mov      dx, 0x28
176AA f7ea           imul     dx
176AC 03c7           add      ax, di
176AE 8d96b8fd       lea      dx, [bp - 0x248]
176B2 03c2           add      ax, dx
176B4 8bd8           mov      bx, ax
176B6 36c60729       mov      byte ptr ss:[bx], 0x29
176BA 47             inc      di
176BB 8b46fa         mov      ax, word ptr [bp - 6]
176BE ba2800         mov      dx, 0x28
176C1 f7ea           imul     dx
176C3 03c7           add      ax, di
176C5 8d96b8fd       lea      dx, [bp - 0x248]
176C9 03c2           add      ax, dx
176CB 8bd8           mov      bx, ax
176CD 36c60700       mov      byte ptr ss:[bx], 0
176D1 ff460c         inc      word ptr [bp + 0xc]
176D4 ff46fa         inc      word ptr [bp - 6]
176D7 ff460c         inc      word ptr [bp + 0xc]
176DA c45e0c         les      bx, ptr [bp + 0xc]
176DD 26803f60       cmp      byte ptr es:[bx], 0x60
176E1 7409           je       0x176ec
176E3 c45e0c         les      bx, ptr [bp + 0xc]
176E6 26803f21       cmp      byte ptr es:[bx], 0x21
176EA 7509           jne      0x176f5
176EC 837efa0a       cmp      word ptr [bp - 6], 0xa
176F0 7d03           jge      0x176f5
176F2 e954ff         jmp      0x17649
176F5 837efe7e       cmp      word ptr [bp - 2], 0x7e
176F9 7450           je       0x1774b
176FB 807e9800       cmp      byte ptr [bp - 0x68], 0
176FF 7427           je       0x17728
17701 8b460a         mov      ax, word ptr [bp + 0xa]
17704 b102           mov      cl, 2
17706 d3e0           shl      ax, cl
17708 c45e06         les      bx, ptr [bp + 6]
1770B 03d8           add      bx, ax
1770D 26c41f         les      bx, ptr es:[bx]
17710 268a470c       mov      al, byte ptr es:[bx + 0xc]
17714 b400           mov      ah, 0
17716 50             push     ax
17717 16             push     ss
17718 8d4698         lea      ax, [bp - 0x68]
1771B 50             push     ax
1771C 9ad43c0000     lcall    0, 0x3cd4
17721 83c406         add      sp, 6
17724 0bc2           or       ax, dx
17726 7479           je       0x177a1
17728 837efa00       cmp      word ptr [bp - 6], 0
1772C 741d           je       0x1774b
1772E ff76fa         push     word ptr [bp - 6]
17731 16             push     ss
17732 8d86b8fd       lea      ax, [bp - 0x248]
17736 50             push     ax
17737 ff760a         push     word ptr [bp + 0xa]
1773A ff7608         push     word ptr [bp + 8]
1773D ff7606         push     word ptr [bp + 6]
17740 0e             push     cs
17741 e87afd         call     0x174be
17744 83c40c         add      sp, 0xc
17747 0bc0           or       ax, ax
17749 7456           je       0x177a1
1774B 837efe7e       cmp      word ptr [bp - 2], 0x7e
1774F 7553           jne      0x177a4
17751 807e9800       cmp      byte ptr [bp - 0x68], 0
17755 7427           je       0x1777e
17757 8b460a         mov      ax, word ptr [bp + 0xa]
1775A b102           mov      cl, 2
1775C d3e0           shl      ax, cl
1775E c45e06         les      bx, ptr [bp + 6]
17761 03d8           add      bx, ax
17763 26c41f         les      bx, ptr es:[bx]
17766 268a470c       mov      al, byte ptr es:[bx + 0xc]
1776A b400           mov      ah, 0
1776C 50             push     ax
1776D 16             push     ss
1776E 8d4698         lea      ax, [bp - 0x68]
17771 50             push     ax
17772 9ad43c0000     lcall    0, 0x3cd4
17777 83c406         add      sp, 6
1777A 0bc2           or       ax, dx
1777C 7523           jne      0x177a1
1777E 837efa00       cmp      word ptr [bp - 6], 0
17782 7420           je       0x177a4
17784 ff76fa         push     word ptr [bp - 6]
17787 16             push     ss
17788 8d86b8fd       lea      ax, [bp - 0x248]
1778C 50             push     ax
1778D ff760a         push     word ptr [bp + 0xa]
17790 ff7608         push     word ptr [bp + 8]
17793 ff7606         push     word ptr [bp + 6]
17796 0e             push     cs
17797 e824fd         call     0x174be
1779A 83c40c         add      sp, 0xc
1779D 0bc0           or       ax, ax
1779F 7403           je       0x177a4
177A1 e9f2fe         jmp      0x17696
177A4 e91c06         jmp      0x17dc3
177A7 33ff           xor      di, di
177A9 ff460c         inc      word ptr [bp + 0xc]
177AC eb0e           jmp      0x177bc
177AE c45e0c         les      bx, ptr [bp + 0xc]
177B1 268a07         mov      al, byte ptr es:[bx]
177B4 8883b8fd       mov      byte ptr [bp + di - 0x248], al
177B8 ff460c         inc      word ptr [bp + 0xc]
177BB 47             inc      di
177BC c45e0c         les      bx, ptr [bp + 0xc]
177BF 26803f00       cmp      byte ptr es:[bx], 0
177C3 7409           je       0x177ce
177C5 c45e0c         les      bx, ptr [bp + 0xc]
177C8 26803f60       cmp      byte ptr es:[bx], 0x60
177CC 75e0           jne      0x177ae
177CE c45e0c         les      bx, ptr [bp + 0xc]
177D1 268a07         mov      al, byte ptr es:[bx]
177D4 b400           mov      ah, 0
177D6 0bc0           or       ax, ax
177D8 7503           jne      0x177dd
177DA e9b9fe         jmp      0x17696
177DD c683b8fd00     mov      byte ptr [bp + di - 0x248], 0
177E2 837efe7e       cmp      word ptr [bp - 2], 0x7e
177E6 7452           je       0x1783a
177E8 8b460a         mov      ax, word ptr [bp + 0xa]
177EB b102           mov      cl, 2
177ED d3e0           shl      ax, cl
177EF c45e06         les      bx, ptr [bp + 6]
177F2 03d8           add      bx, ax
177F4 268b07         mov      ax, word ptr es:[bx]
177F7 051200         add      ax, 0x12
177FA 26ff7702       push     word ptr es:[bx + 2]
177FE 50             push     ax
177FF 16             push     ss
17800 8d86b8fd       lea      ax, [bp - 0x248]
17804 50             push     ax
17805 9ab03d0000     lcall    0, 0x3db0
1780A 83c408         add      sp, 8
1780D 0bc0           or       ax, ax
1780F 7429           je       0x1783a
17811 8b460a         mov      ax, word ptr [bp + 0xa]
17814 b102           mov      cl, 2
17816 d3e0           shl      ax, cl
17818 c45e06         les      bx, ptr [bp + 6]
1781B 03d8           add      bx, ax
1781D 268b07         mov      ax, word ptr es:[bx]
17820 059c00         add      ax, 0x9c
17823 26ff7702       push     word ptr es:[bx + 2]
17827 50             push     ax
17828 16             push     ss
17829 8d86b8fd       lea      ax, [bp - 0x248]
1782D 50             push     ax
1782E 9a113d0000     lcall    0, 0x3d11
17833 83c408         add      sp, 8
17836 0bc0           or       ax, ax
17838 7558           jne      0x17892
1783A 837efe7e       cmp      word ptr [bp - 2], 0x7e
1783E 7555           jne      0x17895
17840 8b460a         mov      ax, word ptr [bp + 0xa]
17843 b102           mov      cl, 2
17845 d3e0           shl      ax, cl
17847 c45e06         les      bx, ptr [bp + 6]
1784A 03d8           add      bx, ax
1784C 268b07         mov      ax, word ptr es:[bx]
1784F 051200         add      ax, 0x12
17852 26ff7702       push     word ptr es:[bx + 2]
17856 50             push     ax
17857 16             push     ss
17858 8d86b8fd       lea      ax, [bp - 0x248]
1785C 50             push     ax
1785D 9ab03d0000     lcall    0, 0x3db0
17862 83c408         add      sp, 8
17865 0bc0           or       ax, ax
17867 7429           je       0x17892
17869 8b460a         mov      ax, word ptr [bp + 0xa]
1786C b102           mov      cl, 2
1786E d3e0           shl      ax, cl
17870 c45e06         les      bx, ptr [bp + 6]
17873 03d8           add      bx, ax
17875 268b07         mov      ax, word ptr es:[bx]
17878 059c00         add      ax, 0x9c
1787B 26ff7702       push     word ptr es:[bx + 2]
1787F 50             push     ax
17880 16             push     ss
17881 8d86b8fd       lea      ax, [bp - 0x248]
17885 50             push     ax
17886 9a113d0000     lcall    0, 0x3d11
1788B 83c408         add      sp, 8
1788E 0bc0           or       ax, ax
17890 7503           jne      0x17895
17892 e901fe         jmp      0x17696
17895 e92b05         jmp      0x17dc3
17898 33ff           xor      di, di
1789A ff460c         inc      word ptr [bp + 0xc]
1789D eb0e           jmp      0x178ad
1789F c45e0c         les      bx, ptr [bp + 0xc]
178A2 268a07         mov      al, byte ptr es:[bx]
178A5 8883b8fd       mov      byte ptr [bp + di - 0x248], al
178A9 ff460c         inc      word ptr [bp + 0xc]
178AC 47             inc      di
178AD c45e0c         les      bx, ptr [bp + 0xc]
178B0 26803f00       cmp      byte ptr es:[bx], 0
178B4 7409           je       0x178bf
178B6 c45e0c         les      bx, ptr [bp + 0xc]
178B9 26803f21       cmp      byte ptr es:[bx], 0x21
178BD 75e0           jne      0x1789f
178BF c45e0c         les      bx, ptr [bp + 0xc]
178C2 268a07         mov      al, byte ptr es:[bx]
178C5 b400           mov      ah, 0
178C7 0bc0           or       ax, ax
178C9 7503           jne      0x178ce
178CB e9c8fd         jmp      0x17696
178CE c683b8fd29     mov      byte ptr [bp + di - 0x248], 0x29
178D3 47             inc      di
178D4 c683b8fd00     mov      byte ptr [bp + di - 0x248], 0
178D9 837efe7e       cmp      word ptr [bp - 2], 0x7e
178DD 7429           je       0x17908
178DF 16             push     ss
178E0 8d86b8fd       lea      ax, [bp - 0x248]
178E4 50             push     ax
178E5 8b460a         mov      ax, word ptr [bp + 0xa]
178E8 b102           mov      cl, 2
178EA d3e0           shl      ax, cl
178EC c45e06         les      bx, ptr [bp + 6]
178EF 03d8           add      bx, ax
178F1 268b07         mov      ax, word ptr es:[bx]
178F4 051c01         add      ax, 0x11c
178F7 26ff7702       push     word ptr es:[bx + 2]
178FB 50             push     ax
178FC 9ad93f0000     lcall    0, 0x3fd9
17901 83c408         add      sp, 8
17904 0bc2           or       ax, dx
17906 742f           je       0x17937
17908 837efe7e       cmp      word ptr [bp - 2], 0x7e
1790C 752c           jne      0x1793a
1790E 16             push     ss
1790F 8d86b8fd       lea      ax, [bp - 0x248]
17913 50             push     ax
17914 8b460a         mov      ax, word ptr [bp + 0xa]
17917 b102           mov      cl, 2
17919 d3e0           shl      ax, cl
1791B c45e06         les      bx, ptr [bp + 6]
1791E 03d8           add      bx, ax
17920 268b07         mov      ax, word ptr es:[bx]
17923 051c01         add      ax, 0x11c
17926 26ff7702       push     word ptr es:[bx + 2]
1792A 50             push     ax
1792B 9ad93f0000     lcall    0, 0x3fd9
17930 83c408         add      sp, 8
17933 0bc2           or       ax, dx
17935 7403           je       0x1793a
17937 e95cfd         jmp      0x17696
1793A e98604         jmp      0x17dc3
1793D 33ff           xor      di, di
1793F ff460c         inc      word ptr [bp + 0xc]
17942 eb0d           jmp      0x17951
17944 c45e0c         les      bx, ptr [bp + 0xc]
17947 268a07         mov      al, byte ptr es:[bx]
1794A 884398         mov      byte ptr [bp + di - 0x68], al
1794D ff460c         inc      word ptr [bp + 0xc]
17950 47             inc      di
17951 c45e0c         les      bx, ptr [bp + 0xc]
17954 26803f00       cmp      byte ptr es:[bx], 0
17958 741b           je       0x17975
1795A c45e0c         les      bx, ptr [bp + 0xc]
1795D 26803f3e       cmp      byte ptr es:[bx], 0x3e
17961 7412           je       0x17975
17963 c45e0c         les      bx, ptr [bp + 0xc]
17966 26803f60       cmp      byte ptr es:[bx], 0x60
1796A 7409           je       0x17975
1796C c45e0c         les      bx, ptr [bp + 0xc]
1796F 26803f21       cmp      byte ptr es:[bx], 0x21
17973 75cf           jne      0x17944
17975 c45e0c         les      bx, ptr [bp + 0xc]
17978 268a07         mov      al, byte ptr es:[bx]
1797B b400           mov      ah, 0
1797D 0bc0           or       ax, ax
1797F 7503           jne      0x17984
17981 e912fd         jmp      0x17696
17984 c6439800       mov      byte ptr [bp + di - 0x68], 0
17988 c746fa0000     mov      word ptr [bp - 6], 0
1798D e98f00         jmp      0x17a1f
17990 33ff           xor      di, di
17992 ff460c         inc      word ptr [bp + 0xc]
17995 eb1f           jmp      0x179b6
17997 8b46fa         mov      ax, word ptr [bp - 6]
1799A ba2800         mov      dx, 0x28
1799D f7ea           imul     dx
1799F 03c7           add      ax, di
179A1 8d96b8fd       lea      dx, [bp - 0x248]
179A5 03c2           add      ax, dx
179A7 c45e0c         les      bx, ptr [bp + 0xc]
179AA 268a17         mov      dl, byte ptr es:[bx]
179AD 8bd8           mov      bx, ax
179AF 368817         mov      byte ptr ss:[bx], dl
179B2 ff460c         inc      word ptr [bp + 0xc]
179B5 47             inc      di
179B6 c45e0c         les      bx, ptr [bp + 0xc]
179B9 26803f00       cmp      byte ptr es:[bx], 0
179BD 7412           je       0x179d1
179BF c45e0c         les      bx, ptr [bp + 0xc]
179C2 26803f60       cmp      byte ptr es:[bx], 0x60
179C6 7409           je       0x179d1
179C8 c45e0c         les      bx, ptr [bp + 0xc]
179CB 26803f21       cmp      byte ptr es:[bx], 0x21
179CF 75c6           jne      0x17997
179D1 c45e0c         les      bx, ptr [bp + 0xc]
179D4 268a07         mov      al, byte ptr es:[bx]
179D7 b400           mov      ah, 0
179D9 0bc0           or       ax, ax
179DB 7503           jne      0x179e0
179DD e9b6fc         jmp      0x17696
179E0 c45e0c         les      bx, ptr [bp + 0xc]
179E3 26803f21       cmp      byte ptr es:[bx], 0x21
179E7 7517           jne      0x17a00
179E9 8b46fa         mov      ax, word ptr [bp - 6]
179EC ba2800         mov      dx, 0x28
179EF f7ea           imul     dx
179F1 03c7           add      ax, di
179F3 8d96b8fd       lea      dx, [bp - 0x248]
179F7 03c2           add      ax, dx
179F9 8bd8           mov      bx, ax
179FB 36c60729       mov      byte ptr ss:[bx], 0x29
179FF 47             inc      di
17A00 8b46fa         mov      ax, word ptr [bp - 6]
17A03 ba2800         mov      dx, 0x28
17A06 f7ea           imul     dx
17A08 03c7           add      ax, di
17A0A 8d96b8fd       lea      dx, [bp - 0x248]
17A0E 03c2           add      ax, dx
17A10 8bd8           mov      bx, ax
17A12 36c60700       mov      byte ptr ss:[bx], 0
17A16 ff460c         inc      word ptr [bp + 0xc]
17A19 ff46fa         inc      word ptr [bp - 6]
17A1C ff460c         inc      word ptr [bp + 0xc]
17A1F c45e0c         les      bx, ptr [bp + 0xc]
17A22 26803f60       cmp      byte ptr es:[bx], 0x60
17A26 7409           je       0x17a31
17A28 c45e0c         les      bx, ptr [bp + 0xc]
17A2B 26803f21       cmp      byte ptr es:[bx], 0x21
17A2F 7509           jne      0x17a3a
17A31 837efa0a       cmp      word ptr [bp - 6], 0xa
17A35 7d03           jge      0x17a3a
17A37 e956ff         jmp      0x17990
17A3A 8b460a         mov      ax, word ptr [bp + 0xa]
17A3D 05aec5         add      ax, 0xc5ae
17A40 8c5ef2         mov      word ptr [bp - 0xe], ds
17A43 8946f0         mov      word ptr [bp - 0x10], ax
17A46 c45e0c         les      bx, ptr [bp + 0xc]
17A49 26807f015b     cmp      byte ptr es:[bx + 1], 0x5b
17A4E 7417           je       0x17a67
17A50 c45e0c         les      bx, ptr [bp + 0xc]
17A53 26807f0160     cmp      byte ptr es:[bx + 1], 0x60
17A58 740d           je       0x17a67
17A5A c45e0c         les      bx, ptr [bp + 0xc]
17A5D 26807f0121     cmp      byte ptr es:[bx + 1], 0x21
17A62 7403           je       0x17a67
17A64 e98d01         jmp      0x17bf4
17A67 33ff           xor      di, di
17A69 83460c02       add      word ptr [bp + 0xc], 2
17A6D eb0e           jmp      0x17a7d
17A6F c45e0c         les      bx, ptr [bp + 0xc]
17A72 268a07         mov      al, byte ptr es:[bx]
17A75 888348ff       mov      byte ptr [bp + di - 0xb8], al
17A79 ff460c         inc      word ptr [bp + 0xc]
17A7C 47             inc      di
17A7D c45e0c         les      bx, ptr [bp + 0xc]
17A80 26803f00       cmp      byte ptr es:[bx], 0
17A84 741b           je       0x17aa1
17A86 c45e0c         les      bx, ptr [bp + 0xc]
17A89 26803f5d       cmp      byte ptr es:[bx], 0x5d
17A8D 7412           je       0x17aa1
17A8F c45e0c         les      bx, ptr [bp + 0xc]
17A92 26803f60       cmp      byte ptr es:[bx], 0x60
17A96 7409           je       0x17aa1
17A98 c45e0c         les      bx, ptr [bp + 0xc]
17A9B 26803f21       cmp      byte ptr es:[bx], 0x21
17A9F 75ce           jne      0x17a6f
17AA1 c45e0c         les      bx, ptr [bp + 0xc]
17AA4 268a07         mov      al, byte ptr es:[bx]
17AA7 b400           mov      ah, 0
17AA9 0bc0           or       ax, ax
17AAB 7503           jne      0x17ab0
17AAD e9e6fb         jmp      0x17696
17AB0 c45e0c         les      bx, ptr [bp + 0xc]
17AB3 26803f21       cmp      byte ptr es:[bx], 0x21
17AB7 7506           jne      0x17abf
17AB9 c68348ff29     mov      byte ptr [bp + di - 0xb8], 0x29
17ABE 47             inc      di
17ABF c68348ff00     mov      byte ptr [bp + di - 0xb8], 0
17AC4 c746f80100     mov      word ptr [bp - 8], 1
17AC9 c45e0c         les      bx, ptr [bp + 0xc]
17ACC 26803f60       cmp      byte ptr es:[bx], 0x60
17AD0 7576           jne      0x17b48
17AD2 ff4e0c         dec      word ptr [bp + 0xc]
17AD5 8b46f2         mov      ax, word ptr [bp - 0xe]
17AD8 8b56f0         mov      dx, word ptr [bp - 0x10]
17ADB 8946f6         mov      word ptr [bp - 0xa], ax
17ADE 8956f4         mov      word ptr [bp - 0xc], dx
17AE1 8b7e0a         mov      di, word ptr [bp + 0xa]
17AE4 eb56           jmp      0x17b3c
17AE6 16             push     ss
17AE7 8d8648ff       lea      ax, [bp - 0xb8]
17AEB 50             push     ax
17AEC 8bc7           mov      ax, di
17AEE b102           mov      cl, 2
17AF0 d3e0           shl      ax, cl
17AF2 c45e06         les      bx, ptr [bp + 6]
17AF5 03d8           add      bx, ax
17AF7 268b07         mov      ax, word ptr es:[bx]
17AFA 051200         add      ax, 0x12
17AFD 26ff7702       push     word ptr es:[bx + 2]
17B01 50             push     ax
17B02 9ab03d0000     lcall    0, 0x3db0
17B07 83c408         add      sp, 8
17B0A 0bc0           or       ax, ax
17B0C 7428           je       0x17b36
17B0E 16             push     ss
17B0F 8d8648ff       lea      ax, [bp - 0xb8]
17B13 50             push     ax
17B14 8bc7           mov      ax, di
17B16 b102           mov      cl, 2
17B18 d3e0           shl      ax, cl
17B1A c45e06         les      bx, ptr [bp + 6]
17B1D 03d8           add      bx, ax
17B1F 268b07         mov      ax, word ptr es:[bx]
17B22 059c00         add      ax, 0x9c
17B25 26ff7702       push     word ptr es:[bx + 2]
17B29 50             push     ax
17B2A 9a113d0000     lcall    0, 0x3d11
17B2F 83c408         add      sp, 8
17B32 0bc0           or       ax, ax
17B34 7502           jne      0x17b38
17B36 eb0d           jmp      0x17b45
17B38 ff46f4         inc      word ptr [bp - 0xc]
17B3B 47             inc      di
17B3C c45ef4         les      bx, ptr [bp - 0xc]
17B3F 26803f00       cmp      byte ptr es:[bx], 0
17B43 75a1           jne      0x17ae6
17B45 e99b00         jmp      0x17be3
17B48 c45e0c         les      bx, ptr [bp + 0xc]
17B4B 26803f21       cmp      byte ptr es:[bx], 0x21
17B4F 754d           jne      0x17b9e
17B51 ff4e0c         dec      word ptr [bp + 0xc]
17B54 8b46f2         mov      ax, word ptr [bp - 0xe]
17B57 8b56f0         mov      dx, word ptr [bp - 0x10]
17B5A 8946f6         mov      word ptr [bp - 0xa], ax
17B5D 8956f4         mov      word ptr [bp - 0xc], dx
17B60 8b7e0a         mov      di, word ptr [bp + 0xa]
17B63 eb2e           jmp      0x17b93
17B65 16             push     ss
17B66 8d8648ff       lea      ax, [bp - 0xb8]
17B6A 50             push     ax
17B6B 8bc7           mov      ax, di
17B6D b102           mov      cl, 2
17B6F d3e0           shl      ax, cl
17B71 c45e06         les      bx, ptr [bp + 6]
17B74 03d8           add      bx, ax
17B76 268b07         mov      ax, word ptr es:[bx]
17B79 051c01         add      ax, 0x11c
17B7C 26ff7702       push     word ptr es:[bx + 2]
17B80 50             push     ax
17B81 9ad93f0000     lcall    0, 0x3fd9
17B86 83c408         add      sp, 8
17B89 0bc2           or       ax, dx
17B8B 7402           je       0x17b8f
17B8D eb0d           jmp      0x17b9c
17B8F ff46f4         inc      word ptr [bp - 0xc]
17B92 47             inc      di
17B93 c45ef4         les      bx, ptr [bp - 0xc]
17B96 26803f00       cmp      byte ptr es:[bx], 0
17B9A 75c9           jne      0x17b65
17B9C eb45           jmp      0x17be3
17B9E ff4e0c         dec      word ptr [bp + 0xc]
17BA1 8b46f2         mov      ax, word ptr [bp - 0xe]
17BA4 8b56f0         mov      dx, word ptr [bp - 0x10]
17BA7 8946f6         mov      word ptr [bp - 0xa], ax
17BAA 8956f4         mov      word ptr [bp - 0xc], dx
17BAD eb2b           jmp      0x17bda
17BAF 8d8648ff       lea      ax, [bp - 0xb8]
17BB3 8c56ee         mov      word ptr [bp - 0x12], ss
17BB6 8946ec         mov      word ptr [bp - 0x14], ax
17BB9 eb13           jmp      0x17bce
17BBB c45ef4         les      bx, ptr [bp - 0xc]
17BBE 268a07         mov      al, byte ptr es:[bx]
17BC1 c45eec         les      bx, ptr [bp - 0x14]
17BC4 263a07         cmp      al, byte ptr es:[bx]
17BC7 7502           jne      0x17bcb
17BC9 eb18           jmp      0x17be3
17BCB ff46ec         inc      word ptr [bp - 0x14]
17BCE c45eec         les      bx, ptr [bp - 0x14]
17BD1 26803f00       cmp      byte ptr es:[bx], 0
17BD5 75e4           jne      0x17bbb
17BD7 ff46f4         inc      word ptr [bp - 0xc]
17BDA c45ef4         les      bx, ptr [bp - 0xc]
17BDD 26803f00       cmp      byte ptr es:[bx], 0
17BE1 75cc           jne      0x17baf
17BE3 c45ef4         les      bx, ptr [bp - 0xc]
17BE6 268a07         mov      al, byte ptr es:[bx]
17BE9 b400           mov      ah, 0
17BEB 0bc0           or       ax, ax
17BED 7503           jne      0x17bf2
17BEF e9a4fa         jmp      0x17696
17BF2 eb53           jmp      0x17c47
17BF4 16             push     ss
17BF5 8d86b8fc       lea      ax, [bp - 0x348]
17BF9 50             push     ax
17BFA ff36ea44       push     word ptr [0x44ea]
17BFE ff36e844       push     word ptr [0x44e8]
17C02 8b460c         mov      ax, word ptr [bp + 0xc]
17C05 40             inc      ax
17C06 ff760e         push     word ptr [bp + 0xe]
17C09 50             push     ax
17C0A 9a8c000421     lcall    0x2104, 0x8c
17C0F 83c40c         add      sp, 0xc
17C12 16             push     ss
17C13 8d86b8fc       lea      ax, [bp - 0x348]
17C17 50             push     ax
17C18 ff76f2         push     word ptr [bp - 0xe]
17C1B ff76f0         push     word ptr [bp - 0x10]
17C1E 9ad93f0000     lcall    0, 0x3fd9
17C23 83c408         add      sp, 8
17C26 8956f6         mov      word ptr [bp - 0xa], dx
17C29 8946f4         mov      word ptr [bp - 0xc], ax
17C2C 8b46f4         mov      ax, word ptr [bp - 0xc]
17C2F 0b46f6         or       ax, word ptr [bp - 0xa]
17C32 7503           jne      0x17c37
17C34 e95ffa         jmp      0x17696
17C37 16             push     ss
17C38 8d86b8fc       lea      ax, [bp - 0x348]
17C3C 50             push     ax
17C3D 9af13d0000     lcall    0, 0x3df1
17C42 59             pop      cx
17C43 59             pop      cx
17C44 8946f8         mov      word ptr [bp - 8], ax
17C47 8b46f2         mov      ax, word ptr [bp - 0xe]
17C4A 8b56f0         mov      dx, word ptr [bp - 0x10]
17C4D 3b46f6         cmp      ax, word ptr [bp - 0xa]
17C50 751d           jne      0x17c6f
17C52 3b56f4         cmp      dx, word ptr [bp - 0xc]
17C55 7518           jne      0x17c6f
17C57 837efe7e       cmp      word ptr [bp - 2], 0x7e
17C5B 7503           jne      0x17c60
17C5D e936fa         jmp      0x17696
17C60 8b46f8         mov      ax, word ptr [bp - 8]
17C63 01460a         add      word ptr [bp + 0xa], ax
17C66 8b46f8         mov      ax, word ptr [bp - 8]
17C69 01460c         add      word ptr [bp + 0xc], ax
17C6C e95e01         jmp      0x17dcd
17C6F c45ef4         les      bx, ptr [bp - 0xc]
17C72 268a07         mov      al, byte ptr es:[bx]
17C75 8846eb         mov      byte ptr [bp - 0x15], al
17C78 c45ef4         les      bx, ptr [bp - 0xc]
17C7B 26c60700       mov      byte ptr es:[bx], 0
17C7F ff76f2         push     word ptr [bp - 0xe]
17C82 ff76f0         push     word ptr [bp - 0x10]
17C85 9af13d0000     lcall    0, 0x3df1
17C8A 59             pop      cx
17C8B 59             pop      cx
17C8C 8946fc         mov      word ptr [bp - 4], ax
17C8F 807e9824       cmp      byte ptr [bp - 0x68], 0x24
17C93 7503           jne      0x17c98
17C95 e99e00         jmp      0x17d36
17C98 837efe7e       cmp      word ptr [bp - 2], 0x7e
17C9C 7442           je       0x17ce0
17C9E 807e9800       cmp      byte ptr [bp - 0x68], 0
17CA2 7416           je       0x17cba
17CA4 ff76f2         push     word ptr [bp - 0xe]
17CA7 ff76f0         push     word ptr [bp - 0x10]
17CAA 16             push     ss
17CAB 8d4698         lea      ax, [bp - 0x68]
17CAE 50             push     ax
17CAF 0e             push     cs
17CB0 e8b4f6         call     0x17367
17CB3 83c408         add      sp, 8
17CB6 0bc0           or       ax, ax
17CB8 746e           je       0x17d28
17CBA 837efa00       cmp      word ptr [bp - 6], 0
17CBE 7420           je       0x17ce0
17CC0 ff76fa         push     word ptr [bp - 6]
17CC3 16             push     ss
17CC4 8d86b8fd       lea      ax, [bp - 0x248]
17CC8 50             push     ax
17CC9 ff76fc         push     word ptr [bp - 4]
17CCC ff760a         push     word ptr [bp + 0xa]
17CCF ff7608         push     word ptr [bp + 8]
17CD2 ff7606         push     word ptr [bp + 6]
17CD5 0e             push     cs
17CD6 e8fcf6         call     0x173d5
17CD9 83c40e         add      sp, 0xe
17CDC 0bc0           or       ax, ax
17CDE 7448           je       0x17d28
17CE0 837efe7e       cmp      word ptr [bp - 2], 0x7e
17CE4 7550           jne      0x17d36
17CE6 807e9800       cmp      byte ptr [bp - 0x68], 0
17CEA 7416           je       0x17d02
17CEC ff76f2         push     word ptr [bp - 0xe]
17CEF ff76f0         push     word ptr [bp - 0x10]
17CF2 16             push     ss
17CF3 8d4698         lea      ax, [bp - 0x68]
17CF6 50             push     ax
17CF7 0e             push     cs
17CF8 e8a3f6         call     0x1739e
17CFB 83c408         add      sp, 8
17CFE 0bc0           or       ax, ax
17D00 7526           jne      0x17d28
17D02 837efa00       cmp      word ptr [bp - 6], 0
17D06 742e           je       0x17d36
17D08 ff76fa         push     word ptr [bp - 6]
17D0B 16             push     ss
17D0C 8d86b8fd       lea      ax, [bp - 0x248]
17D10 50             push     ax
17D11 ff76fc         push     word ptr [bp - 4]
17D14 ff760a         push     word ptr [bp + 0xa]
17D17 ff7608         push     word ptr [bp + 8]
17D1A ff7606         push     word ptr [bp + 6]
17D1D 0e             push     cs
17D1E e8b4f6         call     0x173d5
17D21 83c40e         add      sp, 0xe
17D24 0bc0           or       ax, ax
17D26 740e           je       0x17d36
17D28 c45ef4         les      bx, ptr [bp - 0xc]
17D2B 8a46eb         mov      al, byte ptr [bp - 0x15]
17D2E 268807         mov      byte ptr es:[bx], al
17D31 e962f9         jmp      0x17696
17D34 eb1d           jmp      0x17d53
17D36 c45ef4         les      bx, ptr [bp - 0xc]
17D39 8a46eb         mov      al, byte ptr [bp - 0x15]
17D3C 268807         mov      byte ptr es:[bx], al
17D3F c746fe0000     mov      word ptr [bp - 2], 0
17D44 8b46fc         mov      ax, word ptr [bp - 4]
17D47 0346f8         add      ax, word ptr [bp - 8]
17D4A 01460a         add      word ptr [bp + 0xa], ax
17D4D 8b46f8         mov      ax, word ptr [bp - 8]
17D50 01460c         add      word ptr [bp + 0xc], ax
17D53 eb78           jmp      0x17dcd
17D55 8b460c         mov      ax, word ptr [bp + 0xc]
17D58 40             inc      ax
17D59 ff760e         push     word ptr [bp + 0xe]
17D5C 50             push     ax
17D5D ff760a         push     word ptr [bp + 0xa]
17D60 ff7608         push     word ptr [bp + 8]
17D63 ff7606         push     word ptr [bp + 6]
17D66 0e             push     cs
17D67 e82df8         call     0x17597
17D6A 83c40a         add      sp, 0xa
17D6D 8946fc         mov      word ptr [bp - 4], ax
17D70 837efc00       cmp      word ptr [bp - 4], 0
17D74 7406           je       0x17d7c
17D76 8b46fc         mov      ax, word ptr [bp - 4]
17D79 e91cf9         jmp      0x17698
17D7C eb4a           jmp      0x17dc8
17D7E 837efe7e       cmp      word ptr [bp - 2], 0x7e
17D82 741b           je       0x17d9f
17D84 8b460a         mov      ax, word ptr [bp + 0xa]
17D87 b102           mov      cl, 2
17D89 d3e0           shl      ax, cl
17D8B c45e06         les      bx, ptr [bp + 6]
17D8E 03d8           add      bx, ax
17D90 26c41f         les      bx, ptr es:[bx]
17D93 268a470c       mov      al, byte ptr es:[bx + 0xc]
17D97 c45e0c         les      bx, ptr [bp + 0xc]
17D9A 263a07         cmp      al, byte ptr es:[bx]
17D9D 7521           jne      0x17dc0
17D9F 837efe7e       cmp      word ptr [bp - 2], 0x7e
17DA3 751e           jne      0x17dc3
17DA5 8b460a         mov      ax, word ptr [bp + 0xa]
17DA8 b102           mov      cl, 2
17DAA d3e0           shl      ax, cl
17DAC c45e06         les      bx, ptr [bp + 6]
17DAF 03d8           add      bx, ax
17DB1 26c41f         les      bx, ptr es:[bx]
17DB4 268a470c       mov      al, byte ptr es:[bx + 0xc]
17DB8 c45e0c         les      bx, ptr [bp + 0xc]
17DBB 263a07         cmp      al, byte ptr es:[bx]
17DBE 7503           jne      0x17dc3
17DC0 e9d3f8         jmp      0x17696
17DC3 c746fe0000     mov      word ptr [bp - 2], 0
17DC8 ff460a         inc      word ptr [bp + 0xa]
17DCB eb00           jmp      0x17dcd
17DCD c45e0c         les      bx, ptr [bp + 0xc]
17DD0 268a07         mov      al, byte ptr es:[bx]
17DD3 b400           mov      ah, 0
17DD5 0bc0           or       ax, ax
17DD7 7502           jne      0x17ddb
17DD9 eb0f           jmp      0x17dea
17DDB ff460c         inc      word ptr [bp + 0xc]
17DDE c45e0c         les      bx, ptr [bp + 0xc]
17DE1 26803f00       cmp      byte ptr es:[bx], 0
17DE5 7403           je       0x17dea
17DE7 e9d6f7         jmp      0x175c0
17DEA 8b460a         mov      ax, word ptr [bp + 0xa]
17DED 48             dec      ax
17DEE e9a7f8         jmp      0x17698
17DF1 5f             pop      di
17DF2 5e             pop      si
17DF3 8be5           mov      sp, bp
17DF5 5d             pop      bp
17DF6 cb             retf

; T8 constituent matcher: 0x1FF05..0x20385 (end exclusive)
1FF05 55             push     bp
1FF06 8bec           mov      bp, sp
1FF08 81ec7002       sub      sp, 0x270
1FF0C 56             push     si
1FF0D 57             push     di
1FF0E c746fe0000     mov      word ptr [bp - 2], 0
1FF13 c746fa0000     mov      word ptr [bp - 6], 0
1FF18 e95104         jmp      0x2036c
1FF1B c45e0c         les      bx, ptr [bp + 0xc]
1FF1E 268a07         mov      al, byte ptr es:[bx]
1FF21 b400           mov      ah, 0
1FF23 8946e8         mov      word ptr [bp - 0x18], ax
1FF26 b90400         mov      cx, 4
1FF29 bbb505         mov      bx, 0x5b5
1FF2C 2e8b07         mov      ax, word ptr cs:[bx]
1FF2F 3b46e8         cmp      ax, word ptr [bp - 0x18]
1FF32 7408           je       0x1ff3c
1FF34 83c302         add      bx, 2
1FF37 e2f3           loop     0x1ff2c
1FF39 e9d603         jmp      0x20312
1FF3C 2eff6708       jmp      word ptr cs:[bx + 8]
1FF40 c45e0c         les      bx, ptr [bp + 0xc]
1FF43 268a07         mov      al, byte ptr es:[bx]
1FF46 b400           mov      ah, 0
1FF48 8946fe         mov      word ptr [bp - 2], ax
1FF4B e90d04         jmp      0x2035b
1FF4E 33ff           xor      di, di
1FF50 ff460c         inc      word ptr [bp + 0xc]
1FF53 eb0d           jmp      0x1ff62
1FF55 c45e0c         les      bx, ptr [bp + 0xc]
1FF58 268a07         mov      al, byte ptr es:[bx]
1FF5B 884398         mov      byte ptr [bp + di - 0x68], al
1FF5E ff460c         inc      word ptr [bp + 0xc]
1FF61 47             inc      di
1FF62 c45e0c         les      bx, ptr [bp + 0xc]
1FF65 26803f00       cmp      byte ptr es:[bx], 0
1FF69 7412           je       0x1ff7d
1FF6B c45e0c         les      bx, ptr [bp + 0xc]
1FF6E 26803f5d       cmp      byte ptr es:[bx], 0x5d
1FF72 7409           je       0x1ff7d
1FF74 c45e0c         les      bx, ptr [bp + 0xc]
1FF77 26803f60       cmp      byte ptr es:[bx], 0x60
1FF7B 75d8           jne      0x1ff55
1FF7D c45e0c         les      bx, ptr [bp + 0xc]
1FF80 268a07         mov      al, byte ptr es:[bx]
1FF83 b400           mov      ah, 0
1FF85 0bc0           or       ax, ax
1FF87 7505           jne      0x1ff8e
1FF89 33c0           xor      ax, ax
1FF8B e9f103         jmp      0x2037f
1FF8E c6439800       mov      byte ptr [bp + di - 0x68], 0
1FF92 c746fa0000     mov      word ptr [bp - 6], 0
1FF97 eb65           jmp      0x1fffe
1FF99 33ff           xor      di, di
1FF9B ff460c         inc      word ptr [bp + 0xc]
1FF9E eb1f           jmp      0x1ffbf
1FFA0 8b46fa         mov      ax, word ptr [bp - 6]
1FFA3 ba2800         mov      dx, 0x28
1FFA6 f7ea           imul     dx
1FFA8 03c7           add      ax, di
1FFAA 8d96b8fd       lea      dx, [bp - 0x248]
1FFAE 03c2           add      ax, dx
1FFB0 c45e0c         les      bx, ptr [bp + 0xc]
1FFB3 268a17         mov      dl, byte ptr es:[bx]
1FFB6 8bd8           mov      bx, ax
1FFB8 368817         mov      byte ptr ss:[bx], dl
1FFBB ff460c         inc      word ptr [bp + 0xc]
1FFBE 47             inc      di
1FFBF c45e0c         les      bx, ptr [bp + 0xc]
1FFC2 26803f00       cmp      byte ptr es:[bx], 0
1FFC6 7409           je       0x1ffd1
1FFC8 c45e0c         les      bx, ptr [bp + 0xc]
1FFCB 26803f60       cmp      byte ptr es:[bx], 0x60
1FFCF 75cf           jne      0x1ffa0
1FFD1 c45e0c         les      bx, ptr [bp + 0xc]
1FFD4 268a07         mov      al, byte ptr es:[bx]
1FFD7 b400           mov      ah, 0
1FFD9 0bc0           or       ax, ax
1FFDB 7502           jne      0x1ffdf
1FFDD ebaa           jmp      0x1ff89
1FFDF 8b46fa         mov      ax, word ptr [bp - 6]
1FFE2 ba2800         mov      dx, 0x28
1FFE5 f7ea           imul     dx
1FFE7 03c7           add      ax, di
1FFE9 8d96b8fd       lea      dx, [bp - 0x248]
1FFED 03c2           add      ax, dx
1FFEF 8bd8           mov      bx, ax
1FFF1 36c60700       mov      byte ptr ss:[bx], 0
1FFF5 ff460c         inc      word ptr [bp + 0xc]
1FFF8 ff46fa         inc      word ptr [bp - 6]
1FFFB ff460c         inc      word ptr [bp + 0xc]
1FFFE c45e0c         les      bx, ptr [bp + 0xc]
20001 26803f00       cmp      byte ptr es:[bx], 0
20005 740f           je       0x20016
20007 c45e0c         les      bx, ptr [bp + 0xc]
2000A 26803f60       cmp      byte ptr es:[bx], 0x60
2000E 7506           jne      0x20016
20010 837efa0a       cmp      word ptr [bp - 6], 0xa
20014 7c83           jl       0x1ff99
20016 837efe7e       cmp      word ptr [bp - 2], 0x7e
2001A 742a           je       0x20046
2001C 807e9800       cmp      byte ptr [bp - 0x68], 0
20020 7424           je       0x20046
20022 8b460a         mov      ax, word ptr [bp + 0xa]
20025 ba0c00         mov      dx, 0xc
20028 f7ea           imul     dx
2002A c45e06         les      bx, ptr [bp + 6]
2002D 03d8           add      bx, ax
2002F 268a07         mov      al, byte ptr es:[bx]
20032 b400           mov      ah, 0
20034 50             push     ax
20035 16             push     ss
20036 8d4698         lea      ax, [bp - 0x68]
20039 50             push     ax
2003A 9ad43c0000     lcall    0, 0x3cd4
2003F 83c406         add      sp, 6
20042 0bc2           or       ax, dx
20044 7430           je       0x20076
20046 837efe7e       cmp      word ptr [bp - 2], 0x7e
2004A 752d           jne      0x20079
2004C 807e9800       cmp      byte ptr [bp - 0x68], 0
20050 7427           je       0x20079
20052 8b460a         mov      ax, word ptr [bp + 0xa]
20055 ba0c00         mov      dx, 0xc
20058 f7ea           imul     dx
2005A c45e06         les      bx, ptr [bp + 6]
2005D 03d8           add      bx, ax
2005F 268a07         mov      al, byte ptr es:[bx]
20062 b400           mov      ah, 0
20064 50             push     ax
20065 16             push     ss
20066 8d4698         lea      ax, [bp - 0x68]
20069 50             push     ax
2006A 9ad43c0000     lcall    0, 0x3cd4
2006F 83c406         add      sp, 6
20072 0bc2           or       ax, dx
20074 7403           je       0x20079
20076 e910ff         jmp      0x1ff89
20079 e9d502         jmp      0x20351
2007C 33ff           xor      di, di
2007E ff460c         inc      word ptr [bp + 0xc]
20081 eb0d           jmp      0x20090
20083 c45e0c         les      bx, ptr [bp + 0xc]
20086 268a07         mov      al, byte ptr es:[bx]
20089 884398         mov      byte ptr [bp + di - 0x68], al
2008C ff460c         inc      word ptr [bp + 0xc]
2008F 47             inc      di
20090 c45e0c         les      bx, ptr [bp + 0xc]
20093 26803f00       cmp      byte ptr es:[bx], 0
20097 7412           je       0x200ab
20099 c45e0c         les      bx, ptr [bp + 0xc]
2009C 26803f3e       cmp      byte ptr es:[bx], 0x3e
200A0 7409           je       0x200ab
200A2 c45e0c         les      bx, ptr [bp + 0xc]
200A5 26803f60       cmp      byte ptr es:[bx], 0x60
200A9 75d8           jne      0x20083
200AB c45e0c         les      bx, ptr [bp + 0xc]
200AE 268a07         mov      al, byte ptr es:[bx]
200B1 b400           mov      ah, 0
200B3 0bc0           or       ax, ax
200B5 7503           jne      0x200ba
200B7 e9cffe         jmp      0x1ff89
200BA c6439800       mov      byte ptr [bp + di - 0x68], 0
200BE c746fa0000     mov      word ptr [bp - 6], 0
200C3 eb66           jmp      0x2012b
200C5 33ff           xor      di, di
200C7 ff460c         inc      word ptr [bp + 0xc]
200CA eb1f           jmp      0x200eb
200CC 8b46fa         mov      ax, word ptr [bp - 6]
200CF ba2800         mov      dx, 0x28
200D2 f7ea           imul     dx
200D4 03c7           add      ax, di
200D6 8d96b8fd       lea      dx, [bp - 0x248]
200DA 03c2           add      ax, dx
200DC c45e0c         les      bx, ptr [bp + 0xc]
200DF 268a17         mov      dl, byte ptr es:[bx]
200E2 8bd8           mov      bx, ax
200E4 368817         mov      byte ptr ss:[bx], dl
200E7 ff460c         inc      word ptr [bp + 0xc]
200EA 47             inc      di
200EB c45e0c         les      bx, ptr [bp + 0xc]
200EE 26803f00       cmp      byte ptr es:[bx], 0
200F2 7409           je       0x200fd
200F4 c45e0c         les      bx, ptr [bp + 0xc]
200F7 26803f60       cmp      byte ptr es:[bx], 0x60
200FB 75cf           jne      0x200cc
200FD c45e0c         les      bx, ptr [bp + 0xc]
20100 268a07         mov      al, byte ptr es:[bx]
20103 b400           mov      ah, 0
20105 0bc0           or       ax, ax
20107 7503           jne      0x2010c
20109 e97dfe         jmp      0x1ff89
2010C 8b46fa         mov      ax, word ptr [bp - 6]
2010F ba2800         mov      dx, 0x28
20112 f7ea           imul     dx
20114 03c7           add      ax, di
20116 8d96b8fd       lea      dx, [bp - 0x248]
2011A 03c2           add      ax, dx
2011C 8bd8           mov      bx, ax
2011E 36c60700       mov      byte ptr ss:[bx], 0
20122 ff460c         inc      word ptr [bp + 0xc]
20125 ff46fa         inc      word ptr [bp - 6]
20128 ff460c         inc      word ptr [bp + 0xc]
2012B c45e0c         les      bx, ptr [bp + 0xc]
2012E 26803f00       cmp      byte ptr es:[bx], 0
20132 740f           je       0x20143
20134 c45e0c         les      bx, ptr [bp + 0xc]
20137 26803f60       cmp      byte ptr es:[bx], 0x60
2013B 7506           jne      0x20143
2013D 837efa0a       cmp      word ptr [bp - 6], 0xa
20141 7c82           jl       0x200c5
20143 8b460a         mov      ax, word ptr [bp + 0xa]
20146 05b6c7         add      ax, 0xc7b6
20149 8c5ef2         mov      word ptr [bp - 0xe], ds
2014C 8946f0         mov      word ptr [bp - 0x10], ax
2014F c45e0c         les      bx, ptr [bp + 0xc]
20152 26807f015b     cmp      byte ptr es:[bx + 1], 0x5b
20157 7403           je       0x2015c
20159 e9a000         jmp      0x201fc
2015C 33ff           xor      di, di
2015E 83460c02       add      word ptr [bp + 0xc], 2
20162 eb0e           jmp      0x20172
20164 c45e0c         les      bx, ptr [bp + 0xc]
20167 268a07         mov      al, byte ptr es:[bx]
2016A 888348ff       mov      byte ptr [bp + di - 0xb8], al
2016E ff460c         inc      word ptr [bp + 0xc]
20171 47             inc      di
20172 c45e0c         les      bx, ptr [bp + 0xc]
20175 26803f00       cmp      byte ptr es:[bx], 0
20179 7412           je       0x2018d
2017B c45e0c         les      bx, ptr [bp + 0xc]
2017E 26803f5d       cmp      byte ptr es:[bx], 0x5d
20182 7409           je       0x2018d
20184 c45e0c         les      bx, ptr [bp + 0xc]
20187 26803f60       cmp      byte ptr es:[bx], 0x60
2018B 75d7           jne      0x20164
2018D c45e0c         les      bx, ptr [bp + 0xc]
20190 268a07         mov      al, byte ptr es:[bx]
20193 b400           mov      ah, 0
20195 0bc0           or       ax, ax
20197 7503           jne      0x2019c
20199 e9edfd         jmp      0x1ff89
2019C c68348ff00     mov      byte ptr [bp + di - 0xb8], 0
201A1 c746f80100     mov      word ptr [bp - 8], 1
201A6 ff4e0c         dec      word ptr [bp + 0xc]
201A9 8b46f2         mov      ax, word ptr [bp - 0xe]
201AC 8b56f0         mov      dx, word ptr [bp - 0x10]
201AF 8946f6         mov      word ptr [bp - 0xa], ax
201B2 8956f4         mov      word ptr [bp - 0xc], dx
201B5 eb2b           jmp      0x201e2
201B7 8d8648ff       lea      ax, [bp - 0xb8]
201BB 8c56ee         mov      word ptr [bp - 0x12], ss
201BE 8946ec         mov      word ptr [bp - 0x14], ax
201C1 eb13           jmp      0x201d6
201C3 c45ef4         les      bx, ptr [bp - 0xc]
201C6 268a07         mov      al, byte ptr es:[bx]
201C9 c45eec         les      bx, ptr [bp - 0x14]
201CC 263a07         cmp      al, byte ptr es:[bx]
201CF 7502           jne      0x201d3
201D1 eb18           jmp      0x201eb
201D3 ff46ec         inc      word ptr [bp - 0x14]
201D6 c45eec         les      bx, ptr [bp - 0x14]
201D9 26803f00       cmp      byte ptr es:[bx], 0
201DD 75e4           jne      0x201c3
201DF ff46f4         inc      word ptr [bp - 0xc]
201E2 c45ef4         les      bx, ptr [bp - 0xc]
201E5 26803f00       cmp      byte ptr es:[bx], 0
201E9 75cc           jne      0x201b7
201EB c45ef4         les      bx, ptr [bp - 0xc]
201EE 268a07         mov      al, byte ptr es:[bx]
201F1 b400           mov      ah, 0
201F3 0bc0           or       ax, ax
201F5 7503           jne      0x201fa
201F7 e98ffd         jmp      0x1ff89
201FA eb53           jmp      0x2024f
201FC 16             push     ss
201FD 8d8690fd       lea      ax, [bp - 0x270]
20201 50             push     ax
20202 ff36ea44       push     word ptr [0x44ea]
20206 ff36e844       push     word ptr [0x44e8]
2020A 8b460c         mov      ax, word ptr [bp + 0xc]
2020D 40             inc      ax
2020E ff760e         push     word ptr [bp + 0xe]
20211 50             push     ax
20212 9a8c000421     lcall    0x2104, 0x8c
20217 83c40c         add      sp, 0xc
2021A 16             push     ss
2021B 8d8690fd       lea      ax, [bp - 0x270]
2021F 50             push     ax
20220 ff76f2         push     word ptr [bp - 0xe]
20223 ff76f0         push     word ptr [bp - 0x10]
20226 9ad93f0000     lcall    0, 0x3fd9
2022B 83c408         add      sp, 8
2022E 8956f6         mov      word ptr [bp - 0xa], dx
20231 8946f4         mov      word ptr [bp - 0xc], ax
20234 8b46f4         mov      ax, word ptr [bp - 0xc]
20237 0b46f6         or       ax, word ptr [bp - 0xa]
2023A 7503           jne      0x2023f
2023C e94afd         jmp      0x1ff89
2023F 16             push     ss
20240 8d8690fd       lea      ax, [bp - 0x270]
20244 50             push     ax
20245 9af13d0000     lcall    0, 0x3df1
2024A 59             pop      cx
2024B 59             pop      cx
2024C 8946f8         mov      word ptr [bp - 8], ax
2024F 8b46f2         mov      ax, word ptr [bp - 0xe]
20252 8b56f0         mov      dx, word ptr [bp - 0x10]
20255 3b46f6         cmp      ax, word ptr [bp - 0xa]
20258 751d           jne      0x20277
2025A 3b56f4         cmp      dx, word ptr [bp - 0xc]
2025D 7518           jne      0x20277
2025F 837efe7e       cmp      word ptr [bp - 2], 0x7e
20263 7503           jne      0x20268
20265 e921fd         jmp      0x1ff89
20268 8b46f8         mov      ax, word ptr [bp - 8]
2026B 01460a         add      word ptr [bp + 0xa], ax
2026E 8b46f8         mov      ax, word ptr [bp - 8]
20271 01460c         add      word ptr [bp + 0xc], ax
20274 e9e400         jmp      0x2035b
20277 c45ef4         les      bx, ptr [bp - 0xc]
2027A 268a07         mov      al, byte ptr es:[bx]
2027D 8846eb         mov      byte ptr [bp - 0x15], al
20280 c45ef4         les      bx, ptr [bp - 0xc]
20283 26c60700       mov      byte ptr es:[bx], 0
20287 ff76f2         push     word ptr [bp - 0xe]
2028A ff76f0         push     word ptr [bp - 0x10]
2028D 9af13d0000     lcall    0, 0x3df1
20292 59             pop      cx
20293 59             pop      cx
20294 8946fc         mov      word ptr [bp - 4], ax
20297 807e9824       cmp      byte ptr [bp - 0x68], 0x24
2029B 7454           je       0x202f1
2029D 837efe7e       cmp      word ptr [bp - 2], 0x7e
202A1 741d           je       0x202c0
202A3 807e9800       cmp      byte ptr [bp - 0x68], 0
202A7 7417           je       0x202c0
202A9 ff76f2         push     word ptr [bp - 0xe]
202AC ff76f0         push     word ptr [bp - 0x10]
202AF 16             push     ss
202B0 8d4698         lea      ax, [bp - 0x68]
202B3 50             push     ax
202B4 9a37081313     lcall    0x1313, 0x837
202B9 83c408         add      sp, 8
202BC 0bc0           or       ax, ax
202BE 7423           je       0x202e3
202C0 837efe7e       cmp      word ptr [bp - 2], 0x7e
202C4 752b           jne      0x202f1
202C6 807e9800       cmp      byte ptr [bp - 0x68], 0
202CA 7425           je       0x202f1
202CC ff76f2         push     word ptr [bp - 0xe]
202CF ff76f0         push     word ptr [bp - 0x10]
202D2 16             push     ss
202D3 8d4698         lea      ax, [bp - 0x68]
202D6 50             push     ax
202D7 9a6e081313     lcall    0x1313, 0x86e
202DC 83c408         add      sp, 8
202DF 0bc0           or       ax, ax
202E1 740e           je       0x202f1
202E3 c45ef4         les      bx, ptr [bp - 0xc]
202E6 8a46eb         mov      al, byte ptr [bp - 0x15]
202E9 268807         mov      byte ptr es:[bx], al
202EC e99afc         jmp      0x1ff89
202EF eb1d           jmp      0x2030e
202F1 c45ef4         les      bx, ptr [bp - 0xc]
202F4 8a46eb         mov      al, byte ptr [bp - 0x15]
202F7 268807         mov      byte ptr es:[bx], al
202FA c746fe0000     mov      word ptr [bp - 2], 0
202FF 8b46fc         mov      ax, word ptr [bp - 4]
20302 0346f8         add      ax, word ptr [bp - 8]
20305 01460a         add      word ptr [bp + 0xa], ax
20308 8b46f8         mov      ax, word ptr [bp - 8]
2030B 01460c         add      word ptr [bp + 0xc], ax
2030E eb4b           jmp      0x2035b
20310 eb44           jmp      0x20356
20312 837efe7e       cmp      word ptr [bp - 2], 0x7e
20316 7418           je       0x20330
20318 8b460a         mov      ax, word ptr [bp + 0xa]
2031B ba0c00         mov      dx, 0xc
2031E f7ea           imul     dx
20320 c45e06         les      bx, ptr [bp + 6]
20323 03d8           add      bx, ax
20325 268a07         mov      al, byte ptr es:[bx]
20328 c45e0c         les      bx, ptr [bp + 0xc]
2032B 263a07         cmp      al, byte ptr es:[bx]
2032E 751e           jne      0x2034e
20330 837efe7e       cmp      word ptr [bp - 2], 0x7e
20334 751b           jne      0x20351
20336 8b460a         mov      ax, word ptr [bp + 0xa]
20339 ba0c00         mov      dx, 0xc
2033C f7ea           imul     dx
2033E c45e06         les      bx, ptr [bp + 6]
20341 03d8           add      bx, ax
20343 268a07         mov      al, byte ptr es:[bx]
20346 c45e0c         les      bx, ptr [bp + 0xc]
20349 263a07         cmp      al, byte ptr es:[bx]
2034C 7503           jne      0x20351
2034E e938fc         jmp      0x1ff89
20351 c746fe0000     mov      word ptr [bp - 2], 0
20356 ff460a         inc      word ptr [bp + 0xa]
20359 eb00           jmp      0x2035b
2035B c45e0c         les      bx, ptr [bp + 0xc]
2035E 268a07         mov      al, byte ptr es:[bx]
20361 b400           mov      ah, 0
20363 0bc0           or       ax, ax
20365 7502           jne      0x20369
20367 eb0f           jmp      0x20378
20369 ff460c         inc      word ptr [bp + 0xc]
2036C c45e0c         les      bx, ptr [bp + 0xc]
2036F 26803f00       cmp      byte ptr es:[bx], 0
20373 7403           je       0x20378
20375 e9a3fb         jmp      0x1ff1b
20378 8b460a         mov      ax, word ptr [bp + 0xa]
2037B 48             dec      ax
2037C e90cfc         jmp      0x1ff8b
2037F 5f             pop      di
20380 5e             pop      si
20381 8be5           mov      sp, bp
20383 5d             pop      bp
20384 cb             retf

; Anchor splitter: 0x24ACC..0x24BE2 (end exclusive)
24ACC 55             push     bp
24ACD 8bec           mov      bp, sp
24ACF 8b460e         mov      ax, word ptr [bp + 0xe]
24AD2 0b4610         or       ax, word ptr [bp + 0x10]
24AD5 7407           je       0x24ade
24AD7 c45e0e         les      bx, ptr [bp + 0xe]
24ADA 26c60700       mov      byte ptr es:[bx], 0
24ADE 8b4606         mov      ax, word ptr [bp + 6]
24AE1 0b4608         or       ax, word ptr [bp + 8]
24AE4 750d           jne      0x24af3
24AE6 a1aebd         mov      ax, word ptr [0xbdae]
24AE9 8b16acbd       mov      dx, word ptr [0xbdac]
24AED 894608         mov      word ptr [bp + 8], ax
24AF0 895606         mov      word ptr [bp + 6], dx
24AF3 c706aabd0000   mov      word ptr [0xbdaa], 0
24AF9 c706a8bd0000   mov      word ptr [0xbda8], 0
24AFF 8b4606         mov      ax, word ptr [bp + 6]
24B02 0b4608         or       ax, word ptr [bp + 8]
24B05 7503           jne      0x24b0a
24B07 e9cd00         jmp      0x24bd7
24B0A eb03           jmp      0x24b0f
24B0C ff4606         inc      word ptr [bp + 6]
24B0F c45e06         les      bx, ptr [bp + 6]
24B12 26803f00       cmp      byte ptr es:[bx], 0
24B16 741b           je       0x24b33
24B18 c45e06         les      bx, ptr [bp + 6]
24B1B 268a07         mov      al, byte ptr es:[bx]
24B1E b400           mov      ah, 0
24B20 50             push     ax
24B21 ff760c         push     word ptr [bp + 0xc]
24B24 ff760a         push     word ptr [bp + 0xa]
24B27 9ad43c0000     lcall    0, 0x3cd4
24B2C 83c406         add      sp, 6
24B2F 0bc2           or       ax, dx
24B31 75d9           jne      0x24b0c
24B33 c45e06         les      bx, ptr [bp + 6]
24B36 26803f00       cmp      byte ptr es:[bx], 0
24B3A 7503           jne      0x24b3f
24B3C e98000         jmp      0x24bbf
24B3F 8b4608         mov      ax, word ptr [bp + 8]
24B42 8b5606         mov      dx, word ptr [bp + 6]
24B45 a3aabd         mov      word ptr [0xbdaa], ax
24B48 8916a8bd       mov      word ptr [0xbda8], dx
24B4C ff760c         push     word ptr [bp + 0xc]
24B4F ff760a         push     word ptr [bp + 0xa]
24B52 ff7608         push     word ptr [bp + 8]
24B55 ff7606         push     word ptr [bp + 6]
24B58 9a443f0000     lcall    0, 0x3f44
24B5D 83c408         add      sp, 8
24B60 8916aebd       mov      word ptr [0xbdae], dx
24B64 a3acbd         mov      word ptr [0xbdac], ax
24B67 0bc2           or       ax, dx
24B69 751e           jne      0x24b89
24B6B 8b460e         mov      ax, word ptr [bp + 0xe]
24B6E 0b4610         or       ax, word ptr [bp + 0x10]
24B71 7414           je       0x24b87
24B73 ff7608         push     word ptr [bp + 8]
24B76 ff7606         push     word ptr [bp + 6]
24B79 ff7610         push     word ptr [bp + 0x10]
24B7C ff760e         push     word ptr [bp + 0xe]
24B7F 9a413d0000     lcall    0, 0x3d41
24B84 83c408         add      sp, 8
24B87 eb34           jmp      0x24bbd
24B89 a1acbd         mov      ax, word ptr [0xbdac]
24B8C 2b4606         sub      ax, word ptr [bp + 6]
24B8F a3b0bd         mov      word ptr [0xbdb0], ax
24B92 8b460e         mov      ax, word ptr [bp + 0xe]
24B95 0b4610         or       ax, word ptr [bp + 0x10]
24B98 7423           je       0x24bbd
24B9A ff36b0bd       push     word ptr [0xbdb0]
24B9E ff7608         push     word ptr [bp + 8]
24BA1 ff7606         push     word ptr [bp + 6]
24BA4 ff7610         push     word ptr [bp + 0x10]
24BA7 ff760e         push     word ptr [bp + 0xe]
24BAA 9acf3e0000     lcall    0, 0x3ecf
24BAF 83c40a         add      sp, 0xa
24BB2 c45e0e         les      bx, ptr [bp + 0xe]
24BB5 031eb0bd       add      bx, word ptr [0xbdb0]
24BB9 26c60700       mov      byte ptr es:[bx], 0
24BBD eb18           jmp      0x24bd7
24BBF c706aabd0000   mov      word ptr [0xbdaa], 0
24BC5 c706a8bd0000   mov      word ptr [0xbda8], 0
24BCB c706aebd0000   mov      word ptr [0xbdae], 0
24BD1 c706acbd0000   mov      word ptr [0xbdac], 0
24BD7 8b16aabd       mov      dx, word ptr [0xbdaa]
24BDB a1a8bd         mov      ax, word ptr [0xbda8]
24BDE eb00           jmp      0x24be0
24BE0 5d             pop      bp
24BE1 cb             retf

; CP866 Russian-letter classifier: 0x25D5F..0x25D84 (end exclusive)
25D5F 55             push     bp
25D60 8bec           mov      bp, sp
25D62 8a5606         mov      dl, byte ptr [bp + 6]
25D65 80fa7f         cmp      dl, 0x7f
25D68 7605           jbe      0x25d6f
25D6A 80fab0         cmp      dl, 0xb0
25D6D 720a           jb       0x25d79
25D6F 80fadf         cmp      dl, 0xdf
25D72 760a           jbe      0x25d7e
25D74 80faf2         cmp      dl, 0xf2
25D77 7305           jae      0x25d7e
25D79 b80100         mov      ax, 1
25D7C eb04           jmp      0x25d82
25D7E 33c0           xor      ax, ax
25D80 ebfa           jmp      0x25d7c
25D82 5d             pop      bp
25D83 cb             retf
