-- Preserve every native record, including empty/unsupported paradigm placeholders.
local binary = require "demo.ltpro_binary"
local utils = require "core.utils"
local reader = binary.read(arg[1] or "LTGOLD/LTPRO.EXE")
print('-- Generated by lua demo/extract_morphology.lua; original spelling is intentional.')
print('local data = { nouns = {}, adjectives = {} }')
for _, layout in ipairs(binary.morphology_layouts) do
  local key = 'data.' .. layout.name .. (layout.gender and '[' .. layout.gender .. ']' or '')
  print(string.format('\n-- File 0x%X: %d six-byte records.', layout.offset, layout.count))
  print(key .. ' = {')
  for _, row in ipairs(reader.morphology(layout)) do
    print(string.format('  { %d, %q },', row[1], utils.decode(row[2], false)))
  end
  print('}')
end
print('\nreturn data')
