-- Deterministic extraction; redirect stdout to core/rules.lua to refresh native data.
local binary = require "demo.ltpro_binary"
local encoding = require "core.encoding"
local reader = binary.read(arg[1] or "LTGOLD/LTPRO.EXE")
print('-- Generated by lua demo/extract_ltpro.lua from the unpacked LTPRO image.')
print('-- Handler IDs and guard scalars are native data, not Lua rewrite priorities.')
print('local rules = {}\n')
for _, layout in ipairs(binary.layouts) do
  local key = layout.lua_index and tostring(layout.lua_index) or string.format('%q', layout.lua_key)
  print(string.format('-- %s: file 0x%X, %d records.', layout.name, layout.offset, layout.count))
  print('rules[' .. key .. '] = {')
  for _, record in ipairs(reader.records(layout)) do
    local fields = { string.format('0x%02X', record.flag), string.format('%q', encoding.decode(record.pattern, false)) }
    if record.action then fields[#fields + 1] = string.format('%q', encoding.decode(record.action, false)) end
    if record.endpoint_order ~= nil then fields[#fields + 1] = 'endpoint_order = ' .. record.endpoint_order end
    print('  { ' .. table.concat(fields, ', ') .. ' },')
  end
  print('}\n')
end
print('return rules')
