-- Reproduce all recovered selector-to-code mappings; addresses remain file coordinates.
local binary = require "demo.ltpro_binary"
local reader = binary.read(arg[1] or "LTGOLD/LTPRO.EXE")
print('-- Generated by lua demo/extract_dispatch.lua; LTPRO file offsets, not priorities.')
print('return {')
for _, layout in ipairs(binary.dispatch_layouts) do
  print(string.format('  [%q] = { default = 0x%X,', layout.name, layout.default))
  for _, handler in ipairs(reader.dispatch(layout)) do
    print(string.format('    [%d] = 0x%X,', handler.id, handler.address))
  end
  print('  },')
end
print('}')
