-- Deterministic extraction of every grammar table and string the engine reads
-- from LTPRO's data segment. Run from the repository root:
--   lua demo/extract_ltpro.lua > core/rules.lua
-- The engine reads only core/rules.lua; LTPRO.EXE stays the translation oracle.
package.path = './?.lua;' .. package.path
local binary = require 'demo.ltpro_binary'
local encoding = require 'core.encoding'
local path = arg[1] or 'LTGOLD/LTPRO.EXE'
local file = assert(io.open(path, 'rb'))
local exe = file:read('a')
file:close()
local reader = binary.new(exe)

-- Data-segment helpers: offsets are DS-relative, as the engine addresses them.
local DS = 0x26750
local data = exe:sub(DS + 1)
local function word(at) return string.unpack('<I2', data, at + 1) end
local function cstring(at)
  local stop = assert(data:find('\0', at + 1, true), string.format('unterminated string at 0x%04X', at))
  return data:sub(at + 1, stop - 1)
end

-- CP866 bytes as readable UTF-8; bytes outside the Cyrillic table are escaped.
local function quote(bytes)
  local out = {}
  for i = 1, #bytes do
    local b = bytes:byte(i)
    local c = encoding.character(b)
    if c then out[#out + 1] = c
    elseif b == 0x22 or b == 0x5C then out[#out + 1] = '\\' .. string.char(b)
    elseif b < 0x20 or b >= 0x7F then out[#out + 1] = string.format('\\%03d', b)
    else out[#out + 1] = string.char(b) end
  end
  local text = table.concat(out)
  local loaded = assert(load('return "' .. text .. '"'))()
  assert(encoding.encode(loaded) == bytes, 'string does not round-trip: ' .. text)
  return '"' .. text .. '"'
end

local function emit(...) io.write(string.format(...), '\n') end

emit('-- Generated by lua demo/extract_ltpro.lua from the unpacked LTPRO image.')
emit('-- Every grammar table and string the engine reads from LTPRO\'s data segment.')
emit('-- Handler IDs and guard scalars are native data, not Lua rewrite priorities.')
emit('-- Strings are CP866 shown as UTF-8; core.assets encodes them back.')
emit('local rules = {}\n')

-- Rule tables (file offsets; the engine names them by key).
for _, layout in ipairs(binary.layouts) do
  local key = layout.lua_index and tostring(layout.lua_index) or string.format('%q', layout.lua_key)
  emit('-- %s: file 0x%X, DS 0x%04X, %d records.', layout.name, layout.offset, layout.offset - DS, layout.count)
  emit('rules[%s] = {', key)
  for _, record in ipairs(reader.records(layout)) do
    local fields = { string.format('0x%02X', record.flag), quote(record.pattern) }
    if record.action then fields[#fields + 1] = quote(record.action) end
    if record.endpoint_order ~= nil then fields[#fields + 1] = 'endpoint_order = ' .. record.endpoint_order end
    emit('  { %s },', table.concat(fields, ', '))
  end
  emit('}\n')
end

-- English suffix analysis (0A4F:07F2): ending and the class it assigns, in native order.
emit('-- suffix: file 0x%X, DS 0x%04X: ending and class text, in native order.', binary.suffix_layout.offset,
  binary.suffix_layout.offset - DS)
emit('rules.suffixes = {')
for _, record in ipairs(reader.records(binary.suffix_layout)) do
  emit('  { %s, %s },', quote(record.suffix), quote(record.tag))
end
emit('}\n')

-- Contractions (0A4F:047B), 18-byte rows at DS:0930: ending, class of the
-- inserted word, inserted word, its Russian reading (or none), selector.
emit("-- contractions: DS 0x0930: ending, class, inserted word, Russian reading, selector.")
emit('rules.contractions = {')
do
  local at = 0x0930
  while word(at) ~= 0 do
    local reading = word(at + 12) ~= 0 and quote(cstring(word(at + 12))) or 'false'
    emit('  { %s, %s, %s, %s, %d },', quote(cstring(word(at))), quote(cstring(word(at + 4))),
      quote(cstring(word(at + 8))), reading, word(at + 16))
    at = at + 18
  end
end
emit('}\n')

-- Strings the engine names by DS offset: every such literal in core/*.lua.
local TABLE_BASES = {}
local LISTS = {
  { 0x09E4, nil, "pronouns that take a contracted 's (0A4F:047B)" },
  { 0x5130, 0x42, 'noun ending matchers (ending_matches, class N variant 1)' },
  { 0x53C4, 0x23, 'noun ending matchers (variant 2)' },
  { 0x5522, 0x21, 'noun ending matchers (variant 0)' },
  { 0x566C, 0x1A, 'adjective ending matchers' },
  { 0x58A8, 0x6A, 'verb ending matchers' },
  { 0x5CCC, 0x71, 'verb ending matchers (variant 1)' },
  { 0x6136, 0x2F, 'verb ending matchers (variants g, n, у); rows of the 0x61F2 table' },
  { 0x630C, 2, 'reflexive suffixes' },
  { 0x6314, nil, 'pronoun oblique cases (gen dat acc inst prep), row per pronoun' },
  { 0x6344, nil, 'pronoun nominatives, same rows as 0x6314' },
}
local PARADIGMS = {
  { 0x5238, 66, 'noun-m' }, { 0x5450, 35, 'noun-f' }, { 0x55A6, 33, 'noun-n' },
  { 0x56D4, 78, 'adjective-m' }, { 0x5770, 52, 'adjective-f' }, { 0x580C, 26, 'adjective-n' },
  { 0x5A50, 106, 'verb-imperfective' }, { 0x5E90, 113, 'verb-perfective' },
  { 0x61F2, 47, 'ending replacement (replace_ending)' },
}
-- A list's base and its entries (0x6310 is the second reflexive suffix).
for _, l in ipairs(LISTS) do
  local count = l[2]
  if not count then count = 0; while word(l[1] + count * 4) ~= 0 do count = count + 1 end end
  for i = 0, count do TABLE_BASES[l[1] + i * 4] = true end
end
for _, p in ipairs(PARADIGMS) do TABLE_BASES[p[1]] = true end
TABLE_BASES[0x0930] = true
for _, layout in ipairs(binary.layouts) do TABLE_BASES[layout.offset - DS] = true end

local offsets, words = {}, {}
local listing = assert(io.popen('ls core/*.lua'))
for source in listing:lines() do
  if source ~= 'core/rules.lua' then
    local f = assert(io.open(source))
    local code = f:read('a')
    for literal in code:gmatch('word%(0x(%x+)%)') do words[tonumber(literal, 16)] = true end
    for literal in code:gmatch('0x(%x%x%x%x?)%f[^%x]') do
      local at = tonumber(literal, 16)
      -- 0x8000 is a sign bit, not an offset; smaller literals are tags and fields.
      if at >= 0x400 and at < #data and at ~= 0x8000 and not TABLE_BASES[at] and not words[at] then
        assert(data:byte(at) == 0, string.format('%s: 0x%04X is not the start of a data-segment string', source, at))
        offsets[at] = true
      end
    end
    f:close()
  end
end
listing:close()
local sorted = {}
for at in pairs(offsets) do sorted[#sorted + 1] = at end
table.sort(sorted)
emit('-- Strings named by DS offset in the engine.')
emit('rules.strings = {')
for _, at in ipairs(sorted) do emit('  [0x%04X] = %s,', at, quote(cstring(at))) end
emit('}\n')

-- Pointer lists: one string per 4-byte far pointer.
local word_list = {}
for at in pairs(words) do word_list[#word_list + 1] = at; offsets[at] = nil end
table.sort(word_list)
emit('-- 16-bit values named by DS offset in the engine.')
emit('rules.words = {')
for _, at in ipairs(word_list) do emit('  [0x%04X] = %d,', at, word(at)) end
emit('}\n')

emit('-- Pointer lists: entry i is the string at DS base + 4*i.')
emit('rules.lists = {')
for _, l in ipairs(LISTS) do
  local base, count, note = l[1], l[2], l[3]
  local terminated = count == nil
  if terminated then count = 0; while word(base + count * 4) ~= 0 do count = count + 1 end end
  emit('  -- %s', note)
  emit('  [0x%04X] = {%s', base, terminated and ' terminated = true,' or '')
  for i = 0, count - 1 do
    emit('    [%d] = %s,', i, quote(cstring(word(base + i * 4))))
  end
  emit('  },')
end
emit('}\n')

-- Inflection tables: six-byte rows, a byte count to cut and space-separated endings.
emit('-- Inflection tables: row id = {cut, endings}. "=" keeps the word, "-" has no form.')
emit('rules.paradigms = {')
for _, p in ipairs(PARADIGMS) do
  local base, count, name = p[1], p[2], p[3]
  emit('  -- %s', name)
  emit('  [0x%04X] = {', base)
  for id = 0, count - 1 do
    local at = base + id * 6
    emit('    [%d] = { %d, %s },', id, word(at), quote(cstring(word(at + 2))))
  end
  emit('  },')
end
emit('}\n')
emit('return rules')
