#!/usr/bin/env python3
"""Export a small, reproducible sample of PyMorphy3/OpenCorpora lexemes to Lua.

Install the exact source snapshot with:

    python3 -m pip install -r data/morphology-poc/requirements.txt
    python3 tools/export_opencorpora_poc.py

The resulting Lua file contains only source dictionary forms and grammemes;
the adapter in core/open_morphology.lua selects forms by requested grammemes.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "data/morphology-poc/lexemes.lua"

# Representative OpenCorpora entries from issue 9. The requested POS prevents
# homographs such as "мочь" from silently selecting the first parse.
SAMPLES = [
    ("стол", "NOUN"),
    ("книга", "NOUN"),
    ("окно", "NOUN"),
    ("человек", "NOUN"),
    ("ребёнок", "NOUN"),
    ("время", "NOUN"),
    ("путь", "NOUN"),
    ("читать", "INFN"),
    ("писать", "INFN"),
    ("идти", "INFN"),
    ("быть", "INFN"),
    ("дать", "INFN"),
    ("есть", "INFN"),
    ("хотеть", "INFN"),
    ("мочь", "INFN"),
    ("учиться", "INFN"),
    ("белый", "ADJF"),
]


def lua_string(value: str) -> str:
    # JSON string quoting is valid for the UTF-8 strings used in Lua tables.
    return json.dumps(value, ensure_ascii=False)


def main() -> int:
    try:
        import pymorphy3
    except ImportError:
        print("Install the pinned packages in data/morphology-poc/requirements.txt", file=sys.stderr)
        return 2

    morph = pymorphy3.MorphAnalyzer(lang="ru")
    lexemes = []
    paradigms = {}
    for lemma, wanted_pos in SAMPLES:
        analyses = [p for p in morph.parse(lemma) if p.tag.POS == wanted_pos]
        if not analyses:
            raise SystemExit(f"No {wanted_pos} analysis found for {lemma!r}")
        # Preserve distinct homonymous lexemes that share spelling and POS.
        for analysis in analyses:
            if not analysis.methods_stack:
                raise SystemExit(f"No source paradigm assignment found for {lemma!r}")
            _method, source_form, paradigm_id, form_index = analysis.methods_stack[0]
            paradigm = morph.dictionary.build_paradigm_info(paradigm_id)
            stem = morph.dictionary.build_stem(
                morph.dictionary.paradigms[paradigm_id], form_index, source_form
            )
            rows = [
                (prefix, tuple(sorted(tag.grammemes)), suffix)
                for prefix, tag, suffix in paradigm
            ]
            paradigms[paradigm_id] = rows

            # Check the ready-made prefix/stem/suffix paradigm reconstruction
            # against forms linked to this exact PyMorphy parse.
            reconstructed = {
                (prefix + stem + suffix, tags) for prefix, tags, suffix in rows
            }
            sourced = {
                (form.word, tuple(sorted(form.tag.grammemes)))
                for form in analysis.lexeme
            }
            if sourced != reconstructed:
                raise SystemExit(f"Paradigm reconstruction differs from source forms for {lemma!r}")
            lexemes.append((lemma, wanted_pos, tuple(sorted(analysis.tag.grammemes)),
                            paradigm_id, form_index, stem))

    lines = [
        "-- Generated by tools/export_opencorpora_poc.py; do not edit by hand.",
        "-- Source: pymorphy3-dicts-ru 2.4.417150.4580142, OpenCorpora revision 417150.",
        "return {",
        '  source = "OpenCorpora",',
        '  source_version = "0.92",',
        '  source_revision = "417150",',
        "  paradigms = {",
    ]
    for paradigm_id in sorted(paradigms):
        lines.append(f"    [{paradigm_id}] = {{")
        for prefix, tags, suffix in paradigms[paradigm_id]:
            lines.append(
                "      {prefix = " + lua_string(prefix) + ", tags = {"
                + ", ".join(lua_string(tag) for tag in tags)
                + "}, suffix = " + lua_string(suffix) + "},"
            )
        lines.append("    },")
    lines.extend(["  },", "  lexemes = {"])
    for lemma, pos, lemma_tags, paradigm_id, form_index, stem in lexemes:
        lines.extend(
            [
                "    {",
                f"      lemma = {lua_string(lemma)}, pos = {lua_string(pos)}, paradigm = {paradigm_id}, form_index = {form_index},",
                f"      stem = {lua_string(stem)},",
                "      tags = {" + ", ".join(lua_string(tag) for tag in lemma_tags) + "},",
                "    },",
            ]
        )
    lines.extend(["  },", "}", ""])
    with OUTPUT.open("w", encoding="utf-8", newline="\n") as stream:
        stream.write("\n".join(lines))
    print(f"Wrote {len(lexemes)} lexemes to {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
